LOCAL_PATH := $(call my-dir)/../../../..

include $(CLEAR_VARS)

LOCAL_MODULE := leagor_basic

LOCAL_CFLAGS := -DBORINGSSL_SHARED_LIBRARY -DBORINGSSL_ALLOW_CXX_RUNTIME -DBORINGSSL_NO_STATIC_INITIALIZER -DOPENSSL_SMALL -DOPENSSL_NO_ASM

LOCAL_CFLAGS += -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
LOCAL_CFLAGS += -O3
# opencv
LOCAL_CFLAGS += -D__OPENCV_BUILD=1 -DWITH_CUDA=OFF
# app extra LOCAL_CFLAGS will insert after it
LOCAL_CFLAGS += -DWITH_OPENSSL

LOCAL_CPPFLAGS += -Wno-inconsistent-missing-override -Wno-nonportable-include-path -Wno-narrowing -Wno-enum-constexpr-conversion -DGOOGLE_PROTOBUF_DONT_USE_UNALIGNED
LOCAL_CPPFLAGS += -std=c++17

LOCAL_CPP_EXTENSION := .cxx .cpp .cc

LOCAL_C_INCLUDES := $(LOCAL_PATH)/external/3rdparty \
	$(LOCAL_PATH)/external/boost \
	$(LOCAL_PATH)/external/boringssl/include \
	$(LOCAL_PATH)/external/libros/include \
	$(LOCAL_PATH)/external/mediapipe \
	$(LOCAL_PATH)/external/opencv \
	$(LOCAL_PATH)/external/opencv/3rdparty/carotene/include \
	$(LOCAL_PATH)/external/opencv/autogenerated \
	$(LOCAL_PATH)/external/protobuf/src \
	$(LOCAL_PATH)/external/tensorflow/tensorflow/lite/downloads/eigen \
	$(LOCAL_PATH)/external/zlib \
	$(LOCAL_PATH)/../linker/include/SDL2 \
	$(LOCAL_PATH)/../linker/include/SDL2_image \
	$(LOCAL_PATH)/../linker/include/SDL2_mixer \
	$(LOCAL_PATH)/../linker/include/SDL2_ttf

LOCAL_SRC_FILES := \
	$(subst $(LOCAL_PATH)/,, \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/*.cpp)) \

# only support 64-bit ABIs
LOCAL_LDFLAGS += -L$(LOCAL_PATH)/../linker/android/lib/arm64-v8a -L$(LOCAL_PATH)/../linker/android/lib-android-private/arm64-v8a

LOCAL_LDLIBS := -lz -llog -landroid -lOpenSLES -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -l3rdparty
LOCAL_SHORT_COMMANDS := true

include $(BUILD_SHARED_LIBRARY)