// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: klink.proto

#include "klink.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb2 {
PROTOBUF_CONSTEXPR ttask::ttask(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.aplt_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.task_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ble_device_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.position1_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.position2_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.src_device_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.speech_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.priority_)*/0
  , /*decltype(_impl_.state_)*/0
  , /*decltype(_impl_.iot_src_)*/0
  , /*decltype(_impl_.src_evt_)*/0
  , /*decltype(_impl_.zerotz_t_)*/0
  , /*decltype(_impl_.timed_at_)*/0
  , /*decltype(_impl_.var_at_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ttaskDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ttaskDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ttaskDefaultTypeInternal() {}
  union {
    ttask _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ttaskDefaultTypeInternal _ttask_default_instance_;
PROTOBUF_CONSTEXPR tiot_device::tiot_device(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.device_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.alias_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.icon_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ts_)*/int64_t{0}
  , /*decltype(_impl_.src_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct tiot_deviceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR tiot_deviceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~tiot_deviceDefaultTypeInternal() {}
  union {
    tiot_device _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 tiot_deviceDefaultTypeInternal _tiot_device_default_instance_;
PROTOBUF_CONSTEXPR tklink::tklink(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.iot_tasks_)*/{}
  , /*decltype(_impl_.speech_tasks_)*/{}
  , /*decltype(_impl_.var_tasks_)*/{}
  , /*decltype(_impl_.timed_tasks_)*/{}
  , /*decltype(_impl_.iot_devices_)*/{}
  , /*decltype(_impl_.scene_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.speech_sensor_cfg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.var_sensor_cfg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timed_sensor_cfg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.base_scene_cfg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.task_cpp_cfg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.add_timed_task_cfg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.courselist_cfg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.version_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct tklinkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR tklinkDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~tklinkDefaultTypeInternal() {}
  union {
    tklink _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 tklinkDefaultTypeInternal _tklink_default_instance_;
}  // namespace pb2
namespace pb2 {

// ===================================================================

class ttask::_Internal {
 public:
};

ttask::ttask(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb2.ttask)
}
ttask::ttask(const ttask& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ttask* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.aplt_id_){}
    , decltype(_impl_.task_id_){}
    , decltype(_impl_.ble_device_id_){}
    , decltype(_impl_.position1_){}
    , decltype(_impl_.position2_){}
    , decltype(_impl_.src_device_id_){}
    , decltype(_impl_.speech_id_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.priority_){}
    , decltype(_impl_.state_){}
    , decltype(_impl_.iot_src_){}
    , decltype(_impl_.src_evt_){}
    , decltype(_impl_.zerotz_t_){}
    , decltype(_impl_.timed_at_){}
    , decltype(_impl_.var_at_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.aplt_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aplt_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_aplt_id().empty()) {
    _this->_impl_.aplt_id_.Set(from._internal_aplt_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.task_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.task_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_task_id().empty()) {
    _this->_impl_.task_id_.Set(from._internal_task_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ble_device_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ble_device_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ble_device_id().empty()) {
    _this->_impl_.ble_device_id_.Set(from._internal_ble_device_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.position1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.position1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_position1().empty()) {
    _this->_impl_.position1_.Set(from._internal_position1(), 
      _this->GetArenaForAllocation());
  }
  _impl_.position2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.position2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_position2().empty()) {
    _this->_impl_.position2_.Set(from._internal_position2(), 
      _this->GetArenaForAllocation());
  }
  _impl_.src_device_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_device_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_src_device_id().empty()) {
    _this->_impl_.src_device_id_.Set(from._internal_src_device_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.speech_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.speech_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_speech_id().empty()) {
    _this->_impl_.speech_id_.Set(from._internal_speech_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.var_at_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.var_at_));
  // @@protoc_insertion_point(copy_constructor:pb2.ttask)
}

inline void ttask::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.aplt_id_){}
    , decltype(_impl_.task_id_){}
    , decltype(_impl_.ble_device_id_){}
    , decltype(_impl_.position1_){}
    , decltype(_impl_.position2_){}
    , decltype(_impl_.src_device_id_){}
    , decltype(_impl_.speech_id_){}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.priority_){0}
    , decltype(_impl_.state_){0}
    , decltype(_impl_.iot_src_){0}
    , decltype(_impl_.src_evt_){0}
    , decltype(_impl_.zerotz_t_){0}
    , decltype(_impl_.timed_at_){0}
    , decltype(_impl_.var_at_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.aplt_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aplt_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.task_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.task_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ble_device_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ble_device_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.position1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.position1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.position2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.position2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.src_device_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_device_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.speech_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.speech_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ttask::~ttask() {
  // @@protoc_insertion_point(destructor:pb2.ttask)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ttask::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.aplt_id_.Destroy();
  _impl_.task_id_.Destroy();
  _impl_.ble_device_id_.Destroy();
  _impl_.position1_.Destroy();
  _impl_.position2_.Destroy();
  _impl_.src_device_id_.Destroy();
  _impl_.speech_id_.Destroy();
}

void ttask::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ttask::Clear() {
// @@protoc_insertion_point(message_clear_start:pb2.ttask)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.aplt_id_.ClearToEmpty();
  _impl_.task_id_.ClearToEmpty();
  _impl_.ble_device_id_.ClearToEmpty();
  _impl_.position1_.ClearToEmpty();
  _impl_.position2_.ClearToEmpty();
  _impl_.src_device_id_.ClearToEmpty();
  _impl_.speech_id_.ClearToEmpty();
  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.var_at_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.var_at_));
  _internal_metadata_.Clear<std::string>();
}

const char* ttask::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 priority = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.priority_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string aplt_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_aplt_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string task_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_task_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string ble_device_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_ble_device_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string position1 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_position1();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string position2 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_position2();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 state = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.state_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 iot_src = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.iot_src_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 src_evt = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.src_evt_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string src_device_id = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_src_device_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string speech_id = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 122)) {
          auto str = _internal_mutable_speech_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 zerotz_t = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 160)) {
          _impl_.zerotz_t_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 timed_at = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 168)) {
          _impl_.timed_at_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 var_at = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 200)) {
          _impl_.var_at_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ttask::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb2.ttask)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_type(), target);
  }

  // int32 priority = 2;
  if (this->_internal_priority() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_priority(), target);
  }

  // string aplt_id = 3;
  if (!this->_internal_aplt_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_aplt_id().data(), static_cast<int>(this->_internal_aplt_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.ttask.aplt_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_aplt_id(), target);
  }

  // string task_id = 4;
  if (!this->_internal_task_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_task_id().data(), static_cast<int>(this->_internal_task_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.ttask.task_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_task_id(), target);
  }

  // string ble_device_id = 5;
  if (!this->_internal_ble_device_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ble_device_id().data(), static_cast<int>(this->_internal_ble_device_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.ttask.ble_device_id");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_ble_device_id(), target);
  }

  // string position1 = 6;
  if (!this->_internal_position1().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_position1().data(), static_cast<int>(this->_internal_position1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.ttask.position1");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_position1(), target);
  }

  // string position2 = 7;
  if (!this->_internal_position2().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_position2().data(), static_cast<int>(this->_internal_position2().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.ttask.position2");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_position2(), target);
  }

  // int32 state = 8;
  if (this->_internal_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_state(), target);
  }

  // int32 iot_src = 10;
  if (this->_internal_iot_src() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_iot_src(), target);
  }

  // int32 src_evt = 11;
  if (this->_internal_src_evt() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(11, this->_internal_src_evt(), target);
  }

  // string src_device_id = 12;
  if (!this->_internal_src_device_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_src_device_id().data(), static_cast<int>(this->_internal_src_device_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.ttask.src_device_id");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_src_device_id(), target);
  }

  // string speech_id = 15;
  if (!this->_internal_speech_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_speech_id().data(), static_cast<int>(this->_internal_speech_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.ttask.speech_id");
    target = stream->WriteStringMaybeAliased(
        15, this->_internal_speech_id(), target);
  }

  // int32 zerotz_t = 20;
  if (this->_internal_zerotz_t() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(20, this->_internal_zerotz_t(), target);
  }

  // int32 timed_at = 21;
  if (this->_internal_timed_at() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(21, this->_internal_timed_at(), target);
  }

  // int32 var_at = 25;
  if (this->_internal_var_at() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(25, this->_internal_var_at(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb2.ttask)
  return target;
}

size_t ttask::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb2.ttask)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string aplt_id = 3;
  if (!this->_internal_aplt_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_aplt_id());
  }

  // string task_id = 4;
  if (!this->_internal_task_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_task_id());
  }

  // string ble_device_id = 5;
  if (!this->_internal_ble_device_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ble_device_id());
  }

  // string position1 = 6;
  if (!this->_internal_position1().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_position1());
  }

  // string position2 = 7;
  if (!this->_internal_position2().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_position2());
  }

  // string src_device_id = 12;
  if (!this->_internal_src_device_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_src_device_id());
  }

  // string speech_id = 15;
  if (!this->_internal_speech_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_speech_id());
  }

  // int32 type = 1;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_type());
  }

  // int32 priority = 2;
  if (this->_internal_priority() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_priority());
  }

  // int32 state = 8;
  if (this->_internal_state() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_state());
  }

  // int32 iot_src = 10;
  if (this->_internal_iot_src() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_iot_src());
  }

  // int32 src_evt = 11;
  if (this->_internal_src_evt() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_src_evt());
  }

  // int32 zerotz_t = 20;
  if (this->_internal_zerotz_t() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_zerotz_t());
  }

  // int32 timed_at = 21;
  if (this->_internal_timed_at() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_timed_at());
  }

  // int32 var_at = 25;
  if (this->_internal_var_at() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_var_at());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ttask::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ttask*>(
      &from));
}

void ttask::MergeFrom(const ttask& from) {
  ttask* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:pb2.ttask)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_aplt_id().empty()) {
    _this->_internal_set_aplt_id(from._internal_aplt_id());
  }
  if (!from._internal_task_id().empty()) {
    _this->_internal_set_task_id(from._internal_task_id());
  }
  if (!from._internal_ble_device_id().empty()) {
    _this->_internal_set_ble_device_id(from._internal_ble_device_id());
  }
  if (!from._internal_position1().empty()) {
    _this->_internal_set_position1(from._internal_position1());
  }
  if (!from._internal_position2().empty()) {
    _this->_internal_set_position2(from._internal_position2());
  }
  if (!from._internal_src_device_id().empty()) {
    _this->_internal_set_src_device_id(from._internal_src_device_id());
  }
  if (!from._internal_speech_id().empty()) {
    _this->_internal_set_speech_id(from._internal_speech_id());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_priority() != 0) {
    _this->_internal_set_priority(from._internal_priority());
  }
  if (from._internal_state() != 0) {
    _this->_internal_set_state(from._internal_state());
  }
  if (from._internal_iot_src() != 0) {
    _this->_internal_set_iot_src(from._internal_iot_src());
  }
  if (from._internal_src_evt() != 0) {
    _this->_internal_set_src_evt(from._internal_src_evt());
  }
  if (from._internal_zerotz_t() != 0) {
    _this->_internal_set_zerotz_t(from._internal_zerotz_t());
  }
  if (from._internal_timed_at() != 0) {
    _this->_internal_set_timed_at(from._internal_timed_at());
  }
  if (from._internal_var_at() != 0) {
    _this->_internal_set_var_at(from._internal_var_at());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ttask::CopyFrom(const ttask& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb2.ttask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ttask::IsInitialized() const {
  return true;
}

void ttask::InternalSwap(ttask* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.aplt_id_, lhs_arena,
      &other->_impl_.aplt_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.task_id_, lhs_arena,
      &other->_impl_.task_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ble_device_id_, lhs_arena,
      &other->_impl_.ble_device_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.position1_, lhs_arena,
      &other->_impl_.position1_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.position2_, lhs_arena,
      &other->_impl_.position2_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.src_device_id_, lhs_arena,
      &other->_impl_.src_device_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.speech_id_, lhs_arena,
      &other->_impl_.speech_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ttask, _impl_.var_at_)
      + sizeof(ttask::_impl_.var_at_)
      - PROTOBUF_FIELD_OFFSET(ttask, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

std::string ttask::GetTypeName() const {
  return "pb2.ttask";
}


// ===================================================================

class tiot_device::_Internal {
 public:
};

tiot_device::tiot_device(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb2.tiot_device)
}
tiot_device::tiot_device(const tiot_device& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  tiot_device* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.device_id_){}
    , decltype(_impl_.alias_){}
    , decltype(_impl_.icon_){}
    , decltype(_impl_.ts_){}
    , decltype(_impl_.src_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.device_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.device_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_device_id().empty()) {
    _this->_impl_.device_id_.Set(from._internal_device_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.alias_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alias_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_alias().empty()) {
    _this->_impl_.alias_.Set(from._internal_alias(), 
      _this->GetArenaForAllocation());
  }
  _impl_.icon_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.icon_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_icon().empty()) {
    _this->_impl_.icon_.Set(from._internal_icon(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.ts_, &from._impl_.ts_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.src_) -
    reinterpret_cast<char*>(&_impl_.ts_)) + sizeof(_impl_.src_));
  // @@protoc_insertion_point(copy_constructor:pb2.tiot_device)
}

inline void tiot_device::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.device_id_){}
    , decltype(_impl_.alias_){}
    , decltype(_impl_.icon_){}
    , decltype(_impl_.ts_){int64_t{0}}
    , decltype(_impl_.src_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.device_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.device_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.alias_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alias_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.icon_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.icon_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

tiot_device::~tiot_device() {
  // @@protoc_insertion_point(destructor:pb2.tiot_device)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void tiot_device::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.device_id_.Destroy();
  _impl_.alias_.Destroy();
  _impl_.icon_.Destroy();
}

void tiot_device::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void tiot_device::Clear() {
// @@protoc_insertion_point(message_clear_start:pb2.tiot_device)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_id_.ClearToEmpty();
  _impl_.alias_.ClearToEmpty();
  _impl_.icon_.ClearToEmpty();
  ::memset(&_impl_.ts_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.src_) -
      reinterpret_cast<char*>(&_impl_.ts_)) + sizeof(_impl_.src_));
  _internal_metadata_.Clear<std::string>();
}

const char* tiot_device::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 src = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.src_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string device_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_device_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string alias = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_alias();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string icon = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_icon();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int64 ts = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.ts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* tiot_device::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb2.tiot_device)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 src = 1;
  if (this->_internal_src() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_src(), target);
  }

  // string device_id = 2;
  if (!this->_internal_device_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_device_id().data(), static_cast<int>(this->_internal_device_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tiot_device.device_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_device_id(), target);
  }

  // string alias = 3;
  if (!this->_internal_alias().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_alias().data(), static_cast<int>(this->_internal_alias().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tiot_device.alias");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_alias(), target);
  }

  // string icon = 4;
  if (!this->_internal_icon().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_icon().data(), static_cast<int>(this->_internal_icon().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tiot_device.icon");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_icon(), target);
  }

  // int64 ts = 5;
  if (this->_internal_ts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_ts(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb2.tiot_device)
  return target;
}

size_t tiot_device::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb2.tiot_device)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string device_id = 2;
  if (!this->_internal_device_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_device_id());
  }

  // string alias = 3;
  if (!this->_internal_alias().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_alias());
  }

  // string icon = 4;
  if (!this->_internal_icon().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_icon());
  }

  // int64 ts = 5;
  if (this->_internal_ts() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_ts());
  }

  // int32 src = 1;
  if (this->_internal_src() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_src());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void tiot_device::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const tiot_device*>(
      &from));
}

void tiot_device::MergeFrom(const tiot_device& from) {
  tiot_device* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:pb2.tiot_device)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_device_id().empty()) {
    _this->_internal_set_device_id(from._internal_device_id());
  }
  if (!from._internal_alias().empty()) {
    _this->_internal_set_alias(from._internal_alias());
  }
  if (!from._internal_icon().empty()) {
    _this->_internal_set_icon(from._internal_icon());
  }
  if (from._internal_ts() != 0) {
    _this->_internal_set_ts(from._internal_ts());
  }
  if (from._internal_src() != 0) {
    _this->_internal_set_src(from._internal_src());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void tiot_device::CopyFrom(const tiot_device& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb2.tiot_device)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tiot_device::IsInitialized() const {
  return true;
}

void tiot_device::InternalSwap(tiot_device* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.device_id_, lhs_arena,
      &other->_impl_.device_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.alias_, lhs_arena,
      &other->_impl_.alias_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.icon_, lhs_arena,
      &other->_impl_.icon_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(tiot_device, _impl_.src_)
      + sizeof(tiot_device::_impl_.src_)
      - PROTOBUF_FIELD_OFFSET(tiot_device, _impl_.ts_)>(
          reinterpret_cast<char*>(&_impl_.ts_),
          reinterpret_cast<char*>(&other->_impl_.ts_));
}

std::string tiot_device::GetTypeName() const {
  return "pb2.tiot_device";
}


// ===================================================================

class tklink::_Internal {
 public:
};

tklink::tklink(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb2.tklink)
}
tklink::tklink(const tklink& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  tklink* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.iot_tasks_){from._impl_.iot_tasks_}
    , decltype(_impl_.speech_tasks_){from._impl_.speech_tasks_}
    , decltype(_impl_.var_tasks_){from._impl_.var_tasks_}
    , decltype(_impl_.timed_tasks_){from._impl_.timed_tasks_}
    , decltype(_impl_.iot_devices_){from._impl_.iot_devices_}
    , decltype(_impl_.scene_name_){}
    , decltype(_impl_.speech_sensor_cfg_){}
    , decltype(_impl_.var_sensor_cfg_){}
    , decltype(_impl_.timed_sensor_cfg_){}
    , decltype(_impl_.base_scene_cfg_){}
    , decltype(_impl_.task_cpp_cfg_){}
    , decltype(_impl_.add_timed_task_cfg_){}
    , decltype(_impl_.courselist_cfg_){}
    , decltype(_impl_.version_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.scene_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.scene_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_scene_name().empty()) {
    _this->_impl_.scene_name_.Set(from._internal_scene_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.speech_sensor_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.speech_sensor_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_speech_sensor_cfg().empty()) {
    _this->_impl_.speech_sensor_cfg_.Set(from._internal_speech_sensor_cfg(), 
      _this->GetArenaForAllocation());
  }
  _impl_.var_sensor_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.var_sensor_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_var_sensor_cfg().empty()) {
    _this->_impl_.var_sensor_cfg_.Set(from._internal_var_sensor_cfg(), 
      _this->GetArenaForAllocation());
  }
  _impl_.timed_sensor_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timed_sensor_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_timed_sensor_cfg().empty()) {
    _this->_impl_.timed_sensor_cfg_.Set(from._internal_timed_sensor_cfg(), 
      _this->GetArenaForAllocation());
  }
  _impl_.base_scene_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.base_scene_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_base_scene_cfg().empty()) {
    _this->_impl_.base_scene_cfg_.Set(from._internal_base_scene_cfg(), 
      _this->GetArenaForAllocation());
  }
  _impl_.task_cpp_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.task_cpp_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_task_cpp_cfg().empty()) {
    _this->_impl_.task_cpp_cfg_.Set(from._internal_task_cpp_cfg(), 
      _this->GetArenaForAllocation());
  }
  _impl_.add_timed_task_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.add_timed_task_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_add_timed_task_cfg().empty()) {
    _this->_impl_.add_timed_task_cfg_.Set(from._internal_add_timed_task_cfg(), 
      _this->GetArenaForAllocation());
  }
  _impl_.courselist_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.courselist_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_courselist_cfg().empty()) {
    _this->_impl_.courselist_cfg_.Set(from._internal_courselist_cfg(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.version_ = from._impl_.version_;
  // @@protoc_insertion_point(copy_constructor:pb2.tklink)
}

inline void tklink::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.iot_tasks_){arena}
    , decltype(_impl_.speech_tasks_){arena}
    , decltype(_impl_.var_tasks_){arena}
    , decltype(_impl_.timed_tasks_){arena}
    , decltype(_impl_.iot_devices_){arena}
    , decltype(_impl_.scene_name_){}
    , decltype(_impl_.speech_sensor_cfg_){}
    , decltype(_impl_.var_sensor_cfg_){}
    , decltype(_impl_.timed_sensor_cfg_){}
    , decltype(_impl_.base_scene_cfg_){}
    , decltype(_impl_.task_cpp_cfg_){}
    , decltype(_impl_.add_timed_task_cfg_){}
    , decltype(_impl_.courselist_cfg_){}
    , decltype(_impl_.version_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.scene_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.scene_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.speech_sensor_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.speech_sensor_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.var_sensor_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.var_sensor_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.timed_sensor_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timed_sensor_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.base_scene_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.base_scene_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.task_cpp_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.task_cpp_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.add_timed_task_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.add_timed_task_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.courselist_cfg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.courselist_cfg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

tklink::~tklink() {
  // @@protoc_insertion_point(destructor:pb2.tklink)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void tklink::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.iot_tasks_.~RepeatedPtrField();
  _impl_.speech_tasks_.~RepeatedPtrField();
  _impl_.var_tasks_.~RepeatedPtrField();
  _impl_.timed_tasks_.~RepeatedPtrField();
  _impl_.iot_devices_.~RepeatedPtrField();
  _impl_.scene_name_.Destroy();
  _impl_.speech_sensor_cfg_.Destroy();
  _impl_.var_sensor_cfg_.Destroy();
  _impl_.timed_sensor_cfg_.Destroy();
  _impl_.base_scene_cfg_.Destroy();
  _impl_.task_cpp_cfg_.Destroy();
  _impl_.add_timed_task_cfg_.Destroy();
  _impl_.courselist_cfg_.Destroy();
}

void tklink::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void tklink::Clear() {
// @@protoc_insertion_point(message_clear_start:pb2.tklink)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.iot_tasks_.Clear();
  _impl_.speech_tasks_.Clear();
  _impl_.var_tasks_.Clear();
  _impl_.timed_tasks_.Clear();
  _impl_.iot_devices_.Clear();
  _impl_.scene_name_.ClearToEmpty();
  _impl_.speech_sensor_cfg_.ClearToEmpty();
  _impl_.var_sensor_cfg_.ClearToEmpty();
  _impl_.timed_sensor_cfg_.ClearToEmpty();
  _impl_.base_scene_cfg_.ClearToEmpty();
  _impl_.task_cpp_cfg_.ClearToEmpty();
  _impl_.add_timed_task_cfg_.ClearToEmpty();
  _impl_.courselist_cfg_.ClearToEmpty();
  _impl_.version_ = 0;
  _internal_metadata_.Clear<std::string>();
}

const char* tklink::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string scene_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_scene_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .pb2.ttask iot_tasks = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_iot_tasks(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .pb2.ttask speech_tasks = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_speech_tasks(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .pb2.ttask var_tasks = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_var_tasks(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .pb2.ttask timed_tasks = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_timed_tasks(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .pb2.tiot_device iot_devices = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_iot_devices(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<66>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string speech_sensor_cfg = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_speech_sensor_cfg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string var_sensor_cfg = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_var_sensor_cfg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string timed_sensor_cfg = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_timed_sensor_cfg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string base_scene_cfg = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_base_scene_cfg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string task_cpp_cfg = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 114)) {
          auto str = _internal_mutable_task_cpp_cfg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string add_timed_task_cfg = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 130)) {
          auto str = _internal_mutable_add_timed_task_cfg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string courselist_cfg = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 138)) {
          auto str = _internal_mutable_courselist_cfg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* tklink::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb2.tklink)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 version = 1;
  if (this->_internal_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_version(), target);
  }

  // string scene_name = 3;
  if (!this->_internal_scene_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_scene_name().data(), static_cast<int>(this->_internal_scene_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tklink.scene_name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_scene_name(), target);
  }

  // repeated .pb2.ttask iot_tasks = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_iot_tasks_size()); i < n; i++) {
    const auto& repfield = this->_internal_iot_tasks(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .pb2.ttask speech_tasks = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_speech_tasks_size()); i < n; i++) {
    const auto& repfield = this->_internal_speech_tasks(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .pb2.ttask var_tasks = 6;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_var_tasks_size()); i < n; i++) {
    const auto& repfield = this->_internal_var_tasks(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(6, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .pb2.ttask timed_tasks = 7;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_timed_tasks_size()); i < n; i++) {
    const auto& repfield = this->_internal_timed_tasks(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(7, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .pb2.tiot_device iot_devices = 8;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_iot_devices_size()); i < n; i++) {
    const auto& repfield = this->_internal_iot_devices(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(8, repfield, repfield.GetCachedSize(), target, stream);
  }

  // string speech_sensor_cfg = 10;
  if (!this->_internal_speech_sensor_cfg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_speech_sensor_cfg().data(), static_cast<int>(this->_internal_speech_sensor_cfg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tklink.speech_sensor_cfg");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_speech_sensor_cfg(), target);
  }

  // string var_sensor_cfg = 11;
  if (!this->_internal_var_sensor_cfg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_var_sensor_cfg().data(), static_cast<int>(this->_internal_var_sensor_cfg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tklink.var_sensor_cfg");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_var_sensor_cfg(), target);
  }

  // string timed_sensor_cfg = 12;
  if (!this->_internal_timed_sensor_cfg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timed_sensor_cfg().data(), static_cast<int>(this->_internal_timed_sensor_cfg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tklink.timed_sensor_cfg");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_timed_sensor_cfg(), target);
  }

  // string base_scene_cfg = 13;
  if (!this->_internal_base_scene_cfg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_base_scene_cfg().data(), static_cast<int>(this->_internal_base_scene_cfg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tklink.base_scene_cfg");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_base_scene_cfg(), target);
  }

  // string task_cpp_cfg = 14;
  if (!this->_internal_task_cpp_cfg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_task_cpp_cfg().data(), static_cast<int>(this->_internal_task_cpp_cfg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tklink.task_cpp_cfg");
    target = stream->WriteStringMaybeAliased(
        14, this->_internal_task_cpp_cfg(), target);
  }

  // string add_timed_task_cfg = 16;
  if (!this->_internal_add_timed_task_cfg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_add_timed_task_cfg().data(), static_cast<int>(this->_internal_add_timed_task_cfg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tklink.add_timed_task_cfg");
    target = stream->WriteStringMaybeAliased(
        16, this->_internal_add_timed_task_cfg(), target);
  }

  // string courselist_cfg = 17;
  if (!this->_internal_courselist_cfg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_courselist_cfg().data(), static_cast<int>(this->_internal_courselist_cfg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.tklink.courselist_cfg");
    target = stream->WriteStringMaybeAliased(
        17, this->_internal_courselist_cfg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb2.tklink)
  return target;
}

size_t tklink::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb2.tklink)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb2.ttask iot_tasks = 4;
  total_size += 1UL * this->_internal_iot_tasks_size();
  for (const auto& msg : this->_impl_.iot_tasks_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .pb2.ttask speech_tasks = 5;
  total_size += 1UL * this->_internal_speech_tasks_size();
  for (const auto& msg : this->_impl_.speech_tasks_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .pb2.ttask var_tasks = 6;
  total_size += 1UL * this->_internal_var_tasks_size();
  for (const auto& msg : this->_impl_.var_tasks_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .pb2.ttask timed_tasks = 7;
  total_size += 1UL * this->_internal_timed_tasks_size();
  for (const auto& msg : this->_impl_.timed_tasks_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .pb2.tiot_device iot_devices = 8;
  total_size += 1UL * this->_internal_iot_devices_size();
  for (const auto& msg : this->_impl_.iot_devices_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string scene_name = 3;
  if (!this->_internal_scene_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_scene_name());
  }

  // string speech_sensor_cfg = 10;
  if (!this->_internal_speech_sensor_cfg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_speech_sensor_cfg());
  }

  // string var_sensor_cfg = 11;
  if (!this->_internal_var_sensor_cfg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_var_sensor_cfg());
  }

  // string timed_sensor_cfg = 12;
  if (!this->_internal_timed_sensor_cfg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_timed_sensor_cfg());
  }

  // string base_scene_cfg = 13;
  if (!this->_internal_base_scene_cfg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_base_scene_cfg());
  }

  // string task_cpp_cfg = 14;
  if (!this->_internal_task_cpp_cfg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_task_cpp_cfg());
  }

  // string add_timed_task_cfg = 16;
  if (!this->_internal_add_timed_task_cfg().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_add_timed_task_cfg());
  }

  // string courselist_cfg = 17;
  if (!this->_internal_courselist_cfg().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_courselist_cfg());
  }

  // int32 version = 1;
  if (this->_internal_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_version());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void tklink::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const tklink*>(
      &from));
}

void tklink::MergeFrom(const tklink& from) {
  tklink* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:pb2.tklink)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.iot_tasks_.MergeFrom(from._impl_.iot_tasks_);
  _this->_impl_.speech_tasks_.MergeFrom(from._impl_.speech_tasks_);
  _this->_impl_.var_tasks_.MergeFrom(from._impl_.var_tasks_);
  _this->_impl_.timed_tasks_.MergeFrom(from._impl_.timed_tasks_);
  _this->_impl_.iot_devices_.MergeFrom(from._impl_.iot_devices_);
  if (!from._internal_scene_name().empty()) {
    _this->_internal_set_scene_name(from._internal_scene_name());
  }
  if (!from._internal_speech_sensor_cfg().empty()) {
    _this->_internal_set_speech_sensor_cfg(from._internal_speech_sensor_cfg());
  }
  if (!from._internal_var_sensor_cfg().empty()) {
    _this->_internal_set_var_sensor_cfg(from._internal_var_sensor_cfg());
  }
  if (!from._internal_timed_sensor_cfg().empty()) {
    _this->_internal_set_timed_sensor_cfg(from._internal_timed_sensor_cfg());
  }
  if (!from._internal_base_scene_cfg().empty()) {
    _this->_internal_set_base_scene_cfg(from._internal_base_scene_cfg());
  }
  if (!from._internal_task_cpp_cfg().empty()) {
    _this->_internal_set_task_cpp_cfg(from._internal_task_cpp_cfg());
  }
  if (!from._internal_add_timed_task_cfg().empty()) {
    _this->_internal_set_add_timed_task_cfg(from._internal_add_timed_task_cfg());
  }
  if (!from._internal_courselist_cfg().empty()) {
    _this->_internal_set_courselist_cfg(from._internal_courselist_cfg());
  }
  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void tklink::CopyFrom(const tklink& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb2.tklink)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tklink::IsInitialized() const {
  return true;
}

void tklink::InternalSwap(tklink* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.iot_tasks_.InternalSwap(&other->_impl_.iot_tasks_);
  _impl_.speech_tasks_.InternalSwap(&other->_impl_.speech_tasks_);
  _impl_.var_tasks_.InternalSwap(&other->_impl_.var_tasks_);
  _impl_.timed_tasks_.InternalSwap(&other->_impl_.timed_tasks_);
  _impl_.iot_devices_.InternalSwap(&other->_impl_.iot_devices_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.scene_name_, lhs_arena,
      &other->_impl_.scene_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.speech_sensor_cfg_, lhs_arena,
      &other->_impl_.speech_sensor_cfg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.var_sensor_cfg_, lhs_arena,
      &other->_impl_.var_sensor_cfg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.timed_sensor_cfg_, lhs_arena,
      &other->_impl_.timed_sensor_cfg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.base_scene_cfg_, lhs_arena,
      &other->_impl_.base_scene_cfg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.task_cpp_cfg_, lhs_arena,
      &other->_impl_.task_cpp_cfg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.add_timed_task_cfg_, lhs_arena,
      &other->_impl_.add_timed_task_cfg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.courselist_cfg_, lhs_arena,
      &other->_impl_.courselist_cfg_, rhs_arena
  );
  swap(_impl_.version_, other->_impl_.version_);
}

std::string tklink::GetTypeName() const {
  return "pb2.tklink";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb2
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb2::ttask*
Arena::CreateMaybeMessage< ::pb2::ttask >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb2::ttask >(arena);
}
template<> PROTOBUF_NOINLINE ::pb2::tiot_device*
Arena::CreateMaybeMessage< ::pb2::tiot_device >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb2::tiot_device >(arena);
}
template<> PROTOBUF_NOINLINE ::pb2::tklink*
Arena::CreateMaybeMessage< ::pb2::tklink >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb2::tklink >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
