// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: klink.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_klink_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_klink_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_klink_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_klink_2eproto {
  static const uint32_t offsets[];
};
namespace pb2 {
class tiot_device;
struct tiot_deviceDefaultTypeInternal;
extern tiot_deviceDefaultTypeInternal _tiot_device_default_instance_;
class tklink;
struct tklinkDefaultTypeInternal;
extern tklinkDefaultTypeInternal _tklink_default_instance_;
class ttask;
struct ttaskDefaultTypeInternal;
extern ttaskDefaultTypeInternal _ttask_default_instance_;
}  // namespace pb2
PROTOBUF_NAMESPACE_OPEN
template<> ::pb2::tiot_device* Arena::CreateMaybeMessage<::pb2::tiot_device>(Arena*);
template<> ::pb2::tklink* Arena::CreateMaybeMessage<::pb2::tklink>(Arena*);
template<> ::pb2::ttask* Arena::CreateMaybeMessage<::pb2::ttask>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb2 {

// ===================================================================

class ttask final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pb2.ttask) */ {
 public:
  inline ttask() : ttask(nullptr) {}
  ~ttask() override;
  explicit PROTOBUF_CONSTEXPR ttask(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ttask(const ttask& from);
  ttask(ttask&& from) noexcept
    : ttask() {
    *this = ::std::move(from);
  }

  inline ttask& operator=(const ttask& from) {
    CopyFrom(from);
    return *this;
  }
  inline ttask& operator=(ttask&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ttask& default_instance() {
    return *internal_default_instance();
  }
  static inline const ttask* internal_default_instance() {
    return reinterpret_cast<const ttask*>(
               &_ttask_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ttask& a, ttask& b) {
    a.Swap(&b);
  }
  inline void Swap(ttask* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ttask* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ttask* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ttask>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ttask& from);
  void MergeFrom(const ttask& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ttask* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb2.ttask";
  }
  protected:
  explicit ttask(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApltIdFieldNumber = 3,
    kTaskIdFieldNumber = 4,
    kBleDeviceIdFieldNumber = 5,
    kPosition1FieldNumber = 6,
    kPosition2FieldNumber = 7,
    kSrcDeviceIdFieldNumber = 12,
    kSpeechIdFieldNumber = 15,
    kTypeFieldNumber = 1,
    kPriorityFieldNumber = 2,
    kStateFieldNumber = 8,
    kIotSrcFieldNumber = 10,
    kSrcEvtFieldNumber = 11,
    kZerotzTFieldNumber = 20,
    kTimedAtFieldNumber = 21,
    kVarAtFieldNumber = 25,
  };
  // string aplt_id = 3;
  void clear_aplt_id();
  const std::string& aplt_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_aplt_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_aplt_id();
  PROTOBUF_NODISCARD std::string* release_aplt_id();
  void set_allocated_aplt_id(std::string* aplt_id);
  private:
  const std::string& _internal_aplt_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_aplt_id(const std::string& value);
  std::string* _internal_mutable_aplt_id();
  public:

  // string task_id = 4;
  void clear_task_id();
  const std::string& task_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_task_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_task_id();
  PROTOBUF_NODISCARD std::string* release_task_id();
  void set_allocated_task_id(std::string* task_id);
  private:
  const std::string& _internal_task_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_task_id(const std::string& value);
  std::string* _internal_mutable_task_id();
  public:

  // string ble_device_id = 5;
  void clear_ble_device_id();
  const std::string& ble_device_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ble_device_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ble_device_id();
  PROTOBUF_NODISCARD std::string* release_ble_device_id();
  void set_allocated_ble_device_id(std::string* ble_device_id);
  private:
  const std::string& _internal_ble_device_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ble_device_id(const std::string& value);
  std::string* _internal_mutable_ble_device_id();
  public:

  // string position1 = 6;
  void clear_position1();
  const std::string& position1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_position1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_position1();
  PROTOBUF_NODISCARD std::string* release_position1();
  void set_allocated_position1(std::string* position1);
  private:
  const std::string& _internal_position1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_position1(const std::string& value);
  std::string* _internal_mutable_position1();
  public:

  // string position2 = 7;
  void clear_position2();
  const std::string& position2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_position2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_position2();
  PROTOBUF_NODISCARD std::string* release_position2();
  void set_allocated_position2(std::string* position2);
  private:
  const std::string& _internal_position2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_position2(const std::string& value);
  std::string* _internal_mutable_position2();
  public:

  // string src_device_id = 12;
  void clear_src_device_id();
  const std::string& src_device_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_src_device_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_src_device_id();
  PROTOBUF_NODISCARD std::string* release_src_device_id();
  void set_allocated_src_device_id(std::string* src_device_id);
  private:
  const std::string& _internal_src_device_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_src_device_id(const std::string& value);
  std::string* _internal_mutable_src_device_id();
  public:

  // string speech_id = 15;
  void clear_speech_id();
  const std::string& speech_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_speech_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_speech_id();
  PROTOBUF_NODISCARD std::string* release_speech_id();
  void set_allocated_speech_id(std::string* speech_id);
  private:
  const std::string& _internal_speech_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_speech_id(const std::string& value);
  std::string* _internal_mutable_speech_id();
  public:

  // int32 type = 1;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // int32 priority = 2;
  void clear_priority();
  int32_t priority() const;
  void set_priority(int32_t value);
  private:
  int32_t _internal_priority() const;
  void _internal_set_priority(int32_t value);
  public:

  // int32 state = 8;
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // int32 iot_src = 10;
  void clear_iot_src();
  int32_t iot_src() const;
  void set_iot_src(int32_t value);
  private:
  int32_t _internal_iot_src() const;
  void _internal_set_iot_src(int32_t value);
  public:

  // int32 src_evt = 11;
  void clear_src_evt();
  int32_t src_evt() const;
  void set_src_evt(int32_t value);
  private:
  int32_t _internal_src_evt() const;
  void _internal_set_src_evt(int32_t value);
  public:

  // int32 zerotz_t = 20;
  void clear_zerotz_t();
  int32_t zerotz_t() const;
  void set_zerotz_t(int32_t value);
  private:
  int32_t _internal_zerotz_t() const;
  void _internal_set_zerotz_t(int32_t value);
  public:

  // int32 timed_at = 21;
  void clear_timed_at();
  int32_t timed_at() const;
  void set_timed_at(int32_t value);
  private:
  int32_t _internal_timed_at() const;
  void _internal_set_timed_at(int32_t value);
  public:

  // int32 var_at = 25;
  void clear_var_at();
  int32_t var_at() const;
  void set_var_at(int32_t value);
  private:
  int32_t _internal_var_at() const;
  void _internal_set_var_at(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb2.ttask)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr aplt_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ble_device_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr position1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr position2_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr src_device_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr speech_id_;
    int32_t type_;
    int32_t priority_;
    int32_t state_;
    int32_t iot_src_;
    int32_t src_evt_;
    int32_t zerotz_t_;
    int32_t timed_at_;
    int32_t var_at_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_klink_2eproto;
};
// -------------------------------------------------------------------

class tiot_device final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pb2.tiot_device) */ {
 public:
  inline tiot_device() : tiot_device(nullptr) {}
  ~tiot_device() override;
  explicit PROTOBUF_CONSTEXPR tiot_device(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  tiot_device(const tiot_device& from);
  tiot_device(tiot_device&& from) noexcept
    : tiot_device() {
    *this = ::std::move(from);
  }

  inline tiot_device& operator=(const tiot_device& from) {
    CopyFrom(from);
    return *this;
  }
  inline tiot_device& operator=(tiot_device&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const tiot_device& default_instance() {
    return *internal_default_instance();
  }
  static inline const tiot_device* internal_default_instance() {
    return reinterpret_cast<const tiot_device*>(
               &_tiot_device_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(tiot_device& a, tiot_device& b) {
    a.Swap(&b);
  }
  inline void Swap(tiot_device* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(tiot_device* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  tiot_device* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<tiot_device>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const tiot_device& from);
  void MergeFrom(const tiot_device& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(tiot_device* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb2.tiot_device";
  }
  protected:
  explicit tiot_device(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeviceIdFieldNumber = 2,
    kAliasFieldNumber = 3,
    kIconFieldNumber = 4,
    kTsFieldNumber = 5,
    kSrcFieldNumber = 1,
  };
  // string device_id = 2;
  void clear_device_id();
  const std::string& device_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_device_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_device_id();
  PROTOBUF_NODISCARD std::string* release_device_id();
  void set_allocated_device_id(std::string* device_id);
  private:
  const std::string& _internal_device_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_device_id(const std::string& value);
  std::string* _internal_mutable_device_id();
  public:

  // string alias = 3;
  void clear_alias();
  const std::string& alias() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_alias(ArgT0&& arg0, ArgT... args);
  std::string* mutable_alias();
  PROTOBUF_NODISCARD std::string* release_alias();
  void set_allocated_alias(std::string* alias);
  private:
  const std::string& _internal_alias() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_alias(const std::string& value);
  std::string* _internal_mutable_alias();
  public:

  // string icon = 4;
  void clear_icon();
  const std::string& icon() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_icon(ArgT0&& arg0, ArgT... args);
  std::string* mutable_icon();
  PROTOBUF_NODISCARD std::string* release_icon();
  void set_allocated_icon(std::string* icon);
  private:
  const std::string& _internal_icon() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_icon(const std::string& value);
  std::string* _internal_mutable_icon();
  public:

  // int64 ts = 5;
  void clear_ts();
  int64_t ts() const;
  void set_ts(int64_t value);
  private:
  int64_t _internal_ts() const;
  void _internal_set_ts(int64_t value);
  public:

  // int32 src = 1;
  void clear_src();
  int32_t src() const;
  void set_src(int32_t value);
  private:
  int32_t _internal_src() const;
  void _internal_set_src(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb2.tiot_device)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr alias_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr icon_;
    int64_t ts_;
    int32_t src_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_klink_2eproto;
};
// -------------------------------------------------------------------

class tklink final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pb2.tklink) */ {
 public:
  inline tklink() : tklink(nullptr) {}
  ~tklink() override;
  explicit PROTOBUF_CONSTEXPR tklink(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  tklink(const tklink& from);
  tklink(tklink&& from) noexcept
    : tklink() {
    *this = ::std::move(from);
  }

  inline tklink& operator=(const tklink& from) {
    CopyFrom(from);
    return *this;
  }
  inline tklink& operator=(tklink&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const tklink& default_instance() {
    return *internal_default_instance();
  }
  static inline const tklink* internal_default_instance() {
    return reinterpret_cast<const tklink*>(
               &_tklink_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(tklink& a, tklink& b) {
    a.Swap(&b);
  }
  inline void Swap(tklink* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(tklink* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  tklink* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<tklink>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const tklink& from);
  void MergeFrom(const tklink& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(tklink* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb2.tklink";
  }
  protected:
  explicit tklink(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIotTasksFieldNumber = 4,
    kSpeechTasksFieldNumber = 5,
    kVarTasksFieldNumber = 6,
    kTimedTasksFieldNumber = 7,
    kIotDevicesFieldNumber = 8,
    kSceneNameFieldNumber = 3,
    kSpeechSensorCfgFieldNumber = 10,
    kVarSensorCfgFieldNumber = 11,
    kTimedSensorCfgFieldNumber = 12,
    kBaseSceneCfgFieldNumber = 13,
    kTaskCppCfgFieldNumber = 14,
    kAddTimedTaskCfgFieldNumber = 16,
    kCourselistCfgFieldNumber = 17,
    kVersionFieldNumber = 1,
  };
  // repeated .pb2.ttask iot_tasks = 4;
  int iot_tasks_size() const;
  private:
  int _internal_iot_tasks_size() const;
  public:
  void clear_iot_tasks();
  ::pb2::ttask* mutable_iot_tasks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >*
      mutable_iot_tasks();
  private:
  const ::pb2::ttask& _internal_iot_tasks(int index) const;
  ::pb2::ttask* _internal_add_iot_tasks();
  public:
  const ::pb2::ttask& iot_tasks(int index) const;
  ::pb2::ttask* add_iot_tasks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >&
      iot_tasks() const;

  // repeated .pb2.ttask speech_tasks = 5;
  int speech_tasks_size() const;
  private:
  int _internal_speech_tasks_size() const;
  public:
  void clear_speech_tasks();
  ::pb2::ttask* mutable_speech_tasks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >*
      mutable_speech_tasks();
  private:
  const ::pb2::ttask& _internal_speech_tasks(int index) const;
  ::pb2::ttask* _internal_add_speech_tasks();
  public:
  const ::pb2::ttask& speech_tasks(int index) const;
  ::pb2::ttask* add_speech_tasks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >&
      speech_tasks() const;

  // repeated .pb2.ttask var_tasks = 6;
  int var_tasks_size() const;
  private:
  int _internal_var_tasks_size() const;
  public:
  void clear_var_tasks();
  ::pb2::ttask* mutable_var_tasks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >*
      mutable_var_tasks();
  private:
  const ::pb2::ttask& _internal_var_tasks(int index) const;
  ::pb2::ttask* _internal_add_var_tasks();
  public:
  const ::pb2::ttask& var_tasks(int index) const;
  ::pb2::ttask* add_var_tasks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >&
      var_tasks() const;

  // repeated .pb2.ttask timed_tasks = 7;
  int timed_tasks_size() const;
  private:
  int _internal_timed_tasks_size() const;
  public:
  void clear_timed_tasks();
  ::pb2::ttask* mutable_timed_tasks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >*
      mutable_timed_tasks();
  private:
  const ::pb2::ttask& _internal_timed_tasks(int index) const;
  ::pb2::ttask* _internal_add_timed_tasks();
  public:
  const ::pb2::ttask& timed_tasks(int index) const;
  ::pb2::ttask* add_timed_tasks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >&
      timed_tasks() const;

  // repeated .pb2.tiot_device iot_devices = 8;
  int iot_devices_size() const;
  private:
  int _internal_iot_devices_size() const;
  public:
  void clear_iot_devices();
  ::pb2::tiot_device* mutable_iot_devices(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tiot_device >*
      mutable_iot_devices();
  private:
  const ::pb2::tiot_device& _internal_iot_devices(int index) const;
  ::pb2::tiot_device* _internal_add_iot_devices();
  public:
  const ::pb2::tiot_device& iot_devices(int index) const;
  ::pb2::tiot_device* add_iot_devices();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tiot_device >&
      iot_devices() const;

  // string scene_name = 3;
  void clear_scene_name();
  const std::string& scene_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_scene_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_scene_name();
  PROTOBUF_NODISCARD std::string* release_scene_name();
  void set_allocated_scene_name(std::string* scene_name);
  private:
  const std::string& _internal_scene_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_scene_name(const std::string& value);
  std::string* _internal_mutable_scene_name();
  public:

  // string speech_sensor_cfg = 10;
  void clear_speech_sensor_cfg();
  const std::string& speech_sensor_cfg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_speech_sensor_cfg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_speech_sensor_cfg();
  PROTOBUF_NODISCARD std::string* release_speech_sensor_cfg();
  void set_allocated_speech_sensor_cfg(std::string* speech_sensor_cfg);
  private:
  const std::string& _internal_speech_sensor_cfg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_speech_sensor_cfg(const std::string& value);
  std::string* _internal_mutable_speech_sensor_cfg();
  public:

  // string var_sensor_cfg = 11;
  void clear_var_sensor_cfg();
  const std::string& var_sensor_cfg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_var_sensor_cfg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_var_sensor_cfg();
  PROTOBUF_NODISCARD std::string* release_var_sensor_cfg();
  void set_allocated_var_sensor_cfg(std::string* var_sensor_cfg);
  private:
  const std::string& _internal_var_sensor_cfg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_var_sensor_cfg(const std::string& value);
  std::string* _internal_mutable_var_sensor_cfg();
  public:

  // string timed_sensor_cfg = 12;
  void clear_timed_sensor_cfg();
  const std::string& timed_sensor_cfg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timed_sensor_cfg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timed_sensor_cfg();
  PROTOBUF_NODISCARD std::string* release_timed_sensor_cfg();
  void set_allocated_timed_sensor_cfg(std::string* timed_sensor_cfg);
  private:
  const std::string& _internal_timed_sensor_cfg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timed_sensor_cfg(const std::string& value);
  std::string* _internal_mutable_timed_sensor_cfg();
  public:

  // string base_scene_cfg = 13;
  void clear_base_scene_cfg();
  const std::string& base_scene_cfg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_base_scene_cfg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_base_scene_cfg();
  PROTOBUF_NODISCARD std::string* release_base_scene_cfg();
  void set_allocated_base_scene_cfg(std::string* base_scene_cfg);
  private:
  const std::string& _internal_base_scene_cfg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_base_scene_cfg(const std::string& value);
  std::string* _internal_mutable_base_scene_cfg();
  public:

  // string task_cpp_cfg = 14;
  void clear_task_cpp_cfg();
  const std::string& task_cpp_cfg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_task_cpp_cfg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_task_cpp_cfg();
  PROTOBUF_NODISCARD std::string* release_task_cpp_cfg();
  void set_allocated_task_cpp_cfg(std::string* task_cpp_cfg);
  private:
  const std::string& _internal_task_cpp_cfg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_task_cpp_cfg(const std::string& value);
  std::string* _internal_mutable_task_cpp_cfg();
  public:

  // string add_timed_task_cfg = 16;
  void clear_add_timed_task_cfg();
  const std::string& add_timed_task_cfg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_add_timed_task_cfg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_add_timed_task_cfg();
  PROTOBUF_NODISCARD std::string* release_add_timed_task_cfg();
  void set_allocated_add_timed_task_cfg(std::string* add_timed_task_cfg);
  private:
  const std::string& _internal_add_timed_task_cfg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_add_timed_task_cfg(const std::string& value);
  std::string* _internal_mutable_add_timed_task_cfg();
  public:

  // string courselist_cfg = 17;
  void clear_courselist_cfg();
  const std::string& courselist_cfg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_courselist_cfg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_courselist_cfg();
  PROTOBUF_NODISCARD std::string* release_courselist_cfg();
  void set_allocated_courselist_cfg(std::string* courselist_cfg);
  private:
  const std::string& _internal_courselist_cfg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_courselist_cfg(const std::string& value);
  std::string* _internal_mutable_courselist_cfg();
  public:

  // int32 version = 1;
  void clear_version();
  int32_t version() const;
  void set_version(int32_t value);
  private:
  int32_t _internal_version() const;
  void _internal_set_version(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb2.tklink)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask > iot_tasks_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask > speech_tasks_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask > var_tasks_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask > timed_tasks_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tiot_device > iot_devices_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr scene_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr speech_sensor_cfg_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_sensor_cfg_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timed_sensor_cfg_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr base_scene_cfg_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_cpp_cfg_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr add_timed_task_cfg_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr courselist_cfg_;
    int32_t version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_klink_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ttask

// int32 type = 1;
inline void ttask::clear_type() {
  _impl_.type_ = 0;
}
inline int32_t ttask::_internal_type() const {
  return _impl_.type_;
}
inline int32_t ttask::type() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.type)
  return _internal_type();
}
inline void ttask::_internal_set_type(int32_t value) {
  
  _impl_.type_ = value;
}
inline void ttask::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:pb2.ttask.type)
}

// int32 priority = 2;
inline void ttask::clear_priority() {
  _impl_.priority_ = 0;
}
inline int32_t ttask::_internal_priority() const {
  return _impl_.priority_;
}
inline int32_t ttask::priority() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.priority)
  return _internal_priority();
}
inline void ttask::_internal_set_priority(int32_t value) {
  
  _impl_.priority_ = value;
}
inline void ttask::set_priority(int32_t value) {
  _internal_set_priority(value);
  // @@protoc_insertion_point(field_set:pb2.ttask.priority)
}

// string aplt_id = 3;
inline void ttask::clear_aplt_id() {
  _impl_.aplt_id_.ClearToEmpty();
}
inline const std::string& ttask::aplt_id() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.aplt_id)
  return _internal_aplt_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ttask::set_aplt_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.aplt_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.ttask.aplt_id)
}
inline std::string* ttask::mutable_aplt_id() {
  std::string* _s = _internal_mutable_aplt_id();
  // @@protoc_insertion_point(field_mutable:pb2.ttask.aplt_id)
  return _s;
}
inline const std::string& ttask::_internal_aplt_id() const {
  return _impl_.aplt_id_.Get();
}
inline void ttask::_internal_set_aplt_id(const std::string& value) {
  
  _impl_.aplt_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ttask::_internal_mutable_aplt_id() {
  
  return _impl_.aplt_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ttask::release_aplt_id() {
  // @@protoc_insertion_point(field_release:pb2.ttask.aplt_id)
  return _impl_.aplt_id_.Release();
}
inline void ttask::set_allocated_aplt_id(std::string* aplt_id) {
  if (aplt_id != nullptr) {
    
  } else {
    
  }
  _impl_.aplt_id_.SetAllocated(aplt_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.aplt_id_.IsDefault()) {
    _impl_.aplt_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.ttask.aplt_id)
}

// string task_id = 4;
inline void ttask::clear_task_id() {
  _impl_.task_id_.ClearToEmpty();
}
inline const std::string& ttask::task_id() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.task_id)
  return _internal_task_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ttask::set_task_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.task_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.ttask.task_id)
}
inline std::string* ttask::mutable_task_id() {
  std::string* _s = _internal_mutable_task_id();
  // @@protoc_insertion_point(field_mutable:pb2.ttask.task_id)
  return _s;
}
inline const std::string& ttask::_internal_task_id() const {
  return _impl_.task_id_.Get();
}
inline void ttask::_internal_set_task_id(const std::string& value) {
  
  _impl_.task_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ttask::_internal_mutable_task_id() {
  
  return _impl_.task_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ttask::release_task_id() {
  // @@protoc_insertion_point(field_release:pb2.ttask.task_id)
  return _impl_.task_id_.Release();
}
inline void ttask::set_allocated_task_id(std::string* task_id) {
  if (task_id != nullptr) {
    
  } else {
    
  }
  _impl_.task_id_.SetAllocated(task_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.task_id_.IsDefault()) {
    _impl_.task_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.ttask.task_id)
}

// string ble_device_id = 5;
inline void ttask::clear_ble_device_id() {
  _impl_.ble_device_id_.ClearToEmpty();
}
inline const std::string& ttask::ble_device_id() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.ble_device_id)
  return _internal_ble_device_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ttask::set_ble_device_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ble_device_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.ttask.ble_device_id)
}
inline std::string* ttask::mutable_ble_device_id() {
  std::string* _s = _internal_mutable_ble_device_id();
  // @@protoc_insertion_point(field_mutable:pb2.ttask.ble_device_id)
  return _s;
}
inline const std::string& ttask::_internal_ble_device_id() const {
  return _impl_.ble_device_id_.Get();
}
inline void ttask::_internal_set_ble_device_id(const std::string& value) {
  
  _impl_.ble_device_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ttask::_internal_mutable_ble_device_id() {
  
  return _impl_.ble_device_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ttask::release_ble_device_id() {
  // @@protoc_insertion_point(field_release:pb2.ttask.ble_device_id)
  return _impl_.ble_device_id_.Release();
}
inline void ttask::set_allocated_ble_device_id(std::string* ble_device_id) {
  if (ble_device_id != nullptr) {
    
  } else {
    
  }
  _impl_.ble_device_id_.SetAllocated(ble_device_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ble_device_id_.IsDefault()) {
    _impl_.ble_device_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.ttask.ble_device_id)
}

// string position1 = 6;
inline void ttask::clear_position1() {
  _impl_.position1_.ClearToEmpty();
}
inline const std::string& ttask::position1() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.position1)
  return _internal_position1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ttask::set_position1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.position1_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.ttask.position1)
}
inline std::string* ttask::mutable_position1() {
  std::string* _s = _internal_mutable_position1();
  // @@protoc_insertion_point(field_mutable:pb2.ttask.position1)
  return _s;
}
inline const std::string& ttask::_internal_position1() const {
  return _impl_.position1_.Get();
}
inline void ttask::_internal_set_position1(const std::string& value) {
  
  _impl_.position1_.Set(value, GetArenaForAllocation());
}
inline std::string* ttask::_internal_mutable_position1() {
  
  return _impl_.position1_.Mutable(GetArenaForAllocation());
}
inline std::string* ttask::release_position1() {
  // @@protoc_insertion_point(field_release:pb2.ttask.position1)
  return _impl_.position1_.Release();
}
inline void ttask::set_allocated_position1(std::string* position1) {
  if (position1 != nullptr) {
    
  } else {
    
  }
  _impl_.position1_.SetAllocated(position1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.position1_.IsDefault()) {
    _impl_.position1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.ttask.position1)
}

// string position2 = 7;
inline void ttask::clear_position2() {
  _impl_.position2_.ClearToEmpty();
}
inline const std::string& ttask::position2() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.position2)
  return _internal_position2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ttask::set_position2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.position2_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.ttask.position2)
}
inline std::string* ttask::mutable_position2() {
  std::string* _s = _internal_mutable_position2();
  // @@protoc_insertion_point(field_mutable:pb2.ttask.position2)
  return _s;
}
inline const std::string& ttask::_internal_position2() const {
  return _impl_.position2_.Get();
}
inline void ttask::_internal_set_position2(const std::string& value) {
  
  _impl_.position2_.Set(value, GetArenaForAllocation());
}
inline std::string* ttask::_internal_mutable_position2() {
  
  return _impl_.position2_.Mutable(GetArenaForAllocation());
}
inline std::string* ttask::release_position2() {
  // @@protoc_insertion_point(field_release:pb2.ttask.position2)
  return _impl_.position2_.Release();
}
inline void ttask::set_allocated_position2(std::string* position2) {
  if (position2 != nullptr) {
    
  } else {
    
  }
  _impl_.position2_.SetAllocated(position2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.position2_.IsDefault()) {
    _impl_.position2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.ttask.position2)
}

// int32 state = 8;
inline void ttask::clear_state() {
  _impl_.state_ = 0;
}
inline int32_t ttask::_internal_state() const {
  return _impl_.state_;
}
inline int32_t ttask::state() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.state)
  return _internal_state();
}
inline void ttask::_internal_set_state(int32_t value) {
  
  _impl_.state_ = value;
}
inline void ttask::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:pb2.ttask.state)
}

// int32 iot_src = 10;
inline void ttask::clear_iot_src() {
  _impl_.iot_src_ = 0;
}
inline int32_t ttask::_internal_iot_src() const {
  return _impl_.iot_src_;
}
inline int32_t ttask::iot_src() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.iot_src)
  return _internal_iot_src();
}
inline void ttask::_internal_set_iot_src(int32_t value) {
  
  _impl_.iot_src_ = value;
}
inline void ttask::set_iot_src(int32_t value) {
  _internal_set_iot_src(value);
  // @@protoc_insertion_point(field_set:pb2.ttask.iot_src)
}

// int32 src_evt = 11;
inline void ttask::clear_src_evt() {
  _impl_.src_evt_ = 0;
}
inline int32_t ttask::_internal_src_evt() const {
  return _impl_.src_evt_;
}
inline int32_t ttask::src_evt() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.src_evt)
  return _internal_src_evt();
}
inline void ttask::_internal_set_src_evt(int32_t value) {
  
  _impl_.src_evt_ = value;
}
inline void ttask::set_src_evt(int32_t value) {
  _internal_set_src_evt(value);
  // @@protoc_insertion_point(field_set:pb2.ttask.src_evt)
}

// string src_device_id = 12;
inline void ttask::clear_src_device_id() {
  _impl_.src_device_id_.ClearToEmpty();
}
inline const std::string& ttask::src_device_id() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.src_device_id)
  return _internal_src_device_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ttask::set_src_device_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.src_device_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.ttask.src_device_id)
}
inline std::string* ttask::mutable_src_device_id() {
  std::string* _s = _internal_mutable_src_device_id();
  // @@protoc_insertion_point(field_mutable:pb2.ttask.src_device_id)
  return _s;
}
inline const std::string& ttask::_internal_src_device_id() const {
  return _impl_.src_device_id_.Get();
}
inline void ttask::_internal_set_src_device_id(const std::string& value) {
  
  _impl_.src_device_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ttask::_internal_mutable_src_device_id() {
  
  return _impl_.src_device_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ttask::release_src_device_id() {
  // @@protoc_insertion_point(field_release:pb2.ttask.src_device_id)
  return _impl_.src_device_id_.Release();
}
inline void ttask::set_allocated_src_device_id(std::string* src_device_id) {
  if (src_device_id != nullptr) {
    
  } else {
    
  }
  _impl_.src_device_id_.SetAllocated(src_device_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.src_device_id_.IsDefault()) {
    _impl_.src_device_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.ttask.src_device_id)
}

// string speech_id = 15;
inline void ttask::clear_speech_id() {
  _impl_.speech_id_.ClearToEmpty();
}
inline const std::string& ttask::speech_id() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.speech_id)
  return _internal_speech_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ttask::set_speech_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.speech_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.ttask.speech_id)
}
inline std::string* ttask::mutable_speech_id() {
  std::string* _s = _internal_mutable_speech_id();
  // @@protoc_insertion_point(field_mutable:pb2.ttask.speech_id)
  return _s;
}
inline const std::string& ttask::_internal_speech_id() const {
  return _impl_.speech_id_.Get();
}
inline void ttask::_internal_set_speech_id(const std::string& value) {
  
  _impl_.speech_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ttask::_internal_mutable_speech_id() {
  
  return _impl_.speech_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ttask::release_speech_id() {
  // @@protoc_insertion_point(field_release:pb2.ttask.speech_id)
  return _impl_.speech_id_.Release();
}
inline void ttask::set_allocated_speech_id(std::string* speech_id) {
  if (speech_id != nullptr) {
    
  } else {
    
  }
  _impl_.speech_id_.SetAllocated(speech_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.speech_id_.IsDefault()) {
    _impl_.speech_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.ttask.speech_id)
}

// int32 zerotz_t = 20;
inline void ttask::clear_zerotz_t() {
  _impl_.zerotz_t_ = 0;
}
inline int32_t ttask::_internal_zerotz_t() const {
  return _impl_.zerotz_t_;
}
inline int32_t ttask::zerotz_t() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.zerotz_t)
  return _internal_zerotz_t();
}
inline void ttask::_internal_set_zerotz_t(int32_t value) {
  
  _impl_.zerotz_t_ = value;
}
inline void ttask::set_zerotz_t(int32_t value) {
  _internal_set_zerotz_t(value);
  // @@protoc_insertion_point(field_set:pb2.ttask.zerotz_t)
}

// int32 timed_at = 21;
inline void ttask::clear_timed_at() {
  _impl_.timed_at_ = 0;
}
inline int32_t ttask::_internal_timed_at() const {
  return _impl_.timed_at_;
}
inline int32_t ttask::timed_at() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.timed_at)
  return _internal_timed_at();
}
inline void ttask::_internal_set_timed_at(int32_t value) {
  
  _impl_.timed_at_ = value;
}
inline void ttask::set_timed_at(int32_t value) {
  _internal_set_timed_at(value);
  // @@protoc_insertion_point(field_set:pb2.ttask.timed_at)
}

// int32 var_at = 25;
inline void ttask::clear_var_at() {
  _impl_.var_at_ = 0;
}
inline int32_t ttask::_internal_var_at() const {
  return _impl_.var_at_;
}
inline int32_t ttask::var_at() const {
  // @@protoc_insertion_point(field_get:pb2.ttask.var_at)
  return _internal_var_at();
}
inline void ttask::_internal_set_var_at(int32_t value) {
  
  _impl_.var_at_ = value;
}
inline void ttask::set_var_at(int32_t value) {
  _internal_set_var_at(value);
  // @@protoc_insertion_point(field_set:pb2.ttask.var_at)
}

// -------------------------------------------------------------------

// tiot_device

// int32 src = 1;
inline void tiot_device::clear_src() {
  _impl_.src_ = 0;
}
inline int32_t tiot_device::_internal_src() const {
  return _impl_.src_;
}
inline int32_t tiot_device::src() const {
  // @@protoc_insertion_point(field_get:pb2.tiot_device.src)
  return _internal_src();
}
inline void tiot_device::_internal_set_src(int32_t value) {
  
  _impl_.src_ = value;
}
inline void tiot_device::set_src(int32_t value) {
  _internal_set_src(value);
  // @@protoc_insertion_point(field_set:pb2.tiot_device.src)
}

// string device_id = 2;
inline void tiot_device::clear_device_id() {
  _impl_.device_id_.ClearToEmpty();
}
inline const std::string& tiot_device::device_id() const {
  // @@protoc_insertion_point(field_get:pb2.tiot_device.device_id)
  return _internal_device_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tiot_device::set_device_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.device_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tiot_device.device_id)
}
inline std::string* tiot_device::mutable_device_id() {
  std::string* _s = _internal_mutable_device_id();
  // @@protoc_insertion_point(field_mutable:pb2.tiot_device.device_id)
  return _s;
}
inline const std::string& tiot_device::_internal_device_id() const {
  return _impl_.device_id_.Get();
}
inline void tiot_device::_internal_set_device_id(const std::string& value) {
  
  _impl_.device_id_.Set(value, GetArenaForAllocation());
}
inline std::string* tiot_device::_internal_mutable_device_id() {
  
  return _impl_.device_id_.Mutable(GetArenaForAllocation());
}
inline std::string* tiot_device::release_device_id() {
  // @@protoc_insertion_point(field_release:pb2.tiot_device.device_id)
  return _impl_.device_id_.Release();
}
inline void tiot_device::set_allocated_device_id(std::string* device_id) {
  if (device_id != nullptr) {
    
  } else {
    
  }
  _impl_.device_id_.SetAllocated(device_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.device_id_.IsDefault()) {
    _impl_.device_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tiot_device.device_id)
}

// string alias = 3;
inline void tiot_device::clear_alias() {
  _impl_.alias_.ClearToEmpty();
}
inline const std::string& tiot_device::alias() const {
  // @@protoc_insertion_point(field_get:pb2.tiot_device.alias)
  return _internal_alias();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tiot_device::set_alias(ArgT0&& arg0, ArgT... args) {
 
 _impl_.alias_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tiot_device.alias)
}
inline std::string* tiot_device::mutable_alias() {
  std::string* _s = _internal_mutable_alias();
  // @@protoc_insertion_point(field_mutable:pb2.tiot_device.alias)
  return _s;
}
inline const std::string& tiot_device::_internal_alias() const {
  return _impl_.alias_.Get();
}
inline void tiot_device::_internal_set_alias(const std::string& value) {
  
  _impl_.alias_.Set(value, GetArenaForAllocation());
}
inline std::string* tiot_device::_internal_mutable_alias() {
  
  return _impl_.alias_.Mutable(GetArenaForAllocation());
}
inline std::string* tiot_device::release_alias() {
  // @@protoc_insertion_point(field_release:pb2.tiot_device.alias)
  return _impl_.alias_.Release();
}
inline void tiot_device::set_allocated_alias(std::string* alias) {
  if (alias != nullptr) {
    
  } else {
    
  }
  _impl_.alias_.SetAllocated(alias, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.alias_.IsDefault()) {
    _impl_.alias_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tiot_device.alias)
}

// string icon = 4;
inline void tiot_device::clear_icon() {
  _impl_.icon_.ClearToEmpty();
}
inline const std::string& tiot_device::icon() const {
  // @@protoc_insertion_point(field_get:pb2.tiot_device.icon)
  return _internal_icon();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tiot_device::set_icon(ArgT0&& arg0, ArgT... args) {
 
 _impl_.icon_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tiot_device.icon)
}
inline std::string* tiot_device::mutable_icon() {
  std::string* _s = _internal_mutable_icon();
  // @@protoc_insertion_point(field_mutable:pb2.tiot_device.icon)
  return _s;
}
inline const std::string& tiot_device::_internal_icon() const {
  return _impl_.icon_.Get();
}
inline void tiot_device::_internal_set_icon(const std::string& value) {
  
  _impl_.icon_.Set(value, GetArenaForAllocation());
}
inline std::string* tiot_device::_internal_mutable_icon() {
  
  return _impl_.icon_.Mutable(GetArenaForAllocation());
}
inline std::string* tiot_device::release_icon() {
  // @@protoc_insertion_point(field_release:pb2.tiot_device.icon)
  return _impl_.icon_.Release();
}
inline void tiot_device::set_allocated_icon(std::string* icon) {
  if (icon != nullptr) {
    
  } else {
    
  }
  _impl_.icon_.SetAllocated(icon, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.icon_.IsDefault()) {
    _impl_.icon_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tiot_device.icon)
}

// int64 ts = 5;
inline void tiot_device::clear_ts() {
  _impl_.ts_ = int64_t{0};
}
inline int64_t tiot_device::_internal_ts() const {
  return _impl_.ts_;
}
inline int64_t tiot_device::ts() const {
  // @@protoc_insertion_point(field_get:pb2.tiot_device.ts)
  return _internal_ts();
}
inline void tiot_device::_internal_set_ts(int64_t value) {
  
  _impl_.ts_ = value;
}
inline void tiot_device::set_ts(int64_t value) {
  _internal_set_ts(value);
  // @@protoc_insertion_point(field_set:pb2.tiot_device.ts)
}

// -------------------------------------------------------------------

// tklink

// int32 version = 1;
inline void tklink::clear_version() {
  _impl_.version_ = 0;
}
inline int32_t tklink::_internal_version() const {
  return _impl_.version_;
}
inline int32_t tklink::version() const {
  // @@protoc_insertion_point(field_get:pb2.tklink.version)
  return _internal_version();
}
inline void tklink::_internal_set_version(int32_t value) {
  
  _impl_.version_ = value;
}
inline void tklink::set_version(int32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:pb2.tklink.version)
}

// string scene_name = 3;
inline void tklink::clear_scene_name() {
  _impl_.scene_name_.ClearToEmpty();
}
inline const std::string& tklink::scene_name() const {
  // @@protoc_insertion_point(field_get:pb2.tklink.scene_name)
  return _internal_scene_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tklink::set_scene_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.scene_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tklink.scene_name)
}
inline std::string* tklink::mutable_scene_name() {
  std::string* _s = _internal_mutable_scene_name();
  // @@protoc_insertion_point(field_mutable:pb2.tklink.scene_name)
  return _s;
}
inline const std::string& tklink::_internal_scene_name() const {
  return _impl_.scene_name_.Get();
}
inline void tklink::_internal_set_scene_name(const std::string& value) {
  
  _impl_.scene_name_.Set(value, GetArenaForAllocation());
}
inline std::string* tklink::_internal_mutable_scene_name() {
  
  return _impl_.scene_name_.Mutable(GetArenaForAllocation());
}
inline std::string* tklink::release_scene_name() {
  // @@protoc_insertion_point(field_release:pb2.tklink.scene_name)
  return _impl_.scene_name_.Release();
}
inline void tklink::set_allocated_scene_name(std::string* scene_name) {
  if (scene_name != nullptr) {
    
  } else {
    
  }
  _impl_.scene_name_.SetAllocated(scene_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.scene_name_.IsDefault()) {
    _impl_.scene_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tklink.scene_name)
}

// repeated .pb2.ttask iot_tasks = 4;
inline int tklink::_internal_iot_tasks_size() const {
  return _impl_.iot_tasks_.size();
}
inline int tklink::iot_tasks_size() const {
  return _internal_iot_tasks_size();
}
inline void tklink::clear_iot_tasks() {
  _impl_.iot_tasks_.Clear();
}
inline ::pb2::ttask* tklink::mutable_iot_tasks(int index) {
  // @@protoc_insertion_point(field_mutable:pb2.tklink.iot_tasks)
  return _impl_.iot_tasks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >*
tklink::mutable_iot_tasks() {
  // @@protoc_insertion_point(field_mutable_list:pb2.tklink.iot_tasks)
  return &_impl_.iot_tasks_;
}
inline const ::pb2::ttask& tklink::_internal_iot_tasks(int index) const {
  return _impl_.iot_tasks_.Get(index);
}
inline const ::pb2::ttask& tklink::iot_tasks(int index) const {
  // @@protoc_insertion_point(field_get:pb2.tklink.iot_tasks)
  return _internal_iot_tasks(index);
}
inline ::pb2::ttask* tklink::_internal_add_iot_tasks() {
  return _impl_.iot_tasks_.Add();
}
inline ::pb2::ttask* tklink::add_iot_tasks() {
  ::pb2::ttask* _add = _internal_add_iot_tasks();
  // @@protoc_insertion_point(field_add:pb2.tklink.iot_tasks)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >&
tklink::iot_tasks() const {
  // @@protoc_insertion_point(field_list:pb2.tklink.iot_tasks)
  return _impl_.iot_tasks_;
}

// repeated .pb2.ttask speech_tasks = 5;
inline int tklink::_internal_speech_tasks_size() const {
  return _impl_.speech_tasks_.size();
}
inline int tklink::speech_tasks_size() const {
  return _internal_speech_tasks_size();
}
inline void tklink::clear_speech_tasks() {
  _impl_.speech_tasks_.Clear();
}
inline ::pb2::ttask* tklink::mutable_speech_tasks(int index) {
  // @@protoc_insertion_point(field_mutable:pb2.tklink.speech_tasks)
  return _impl_.speech_tasks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >*
tklink::mutable_speech_tasks() {
  // @@protoc_insertion_point(field_mutable_list:pb2.tklink.speech_tasks)
  return &_impl_.speech_tasks_;
}
inline const ::pb2::ttask& tklink::_internal_speech_tasks(int index) const {
  return _impl_.speech_tasks_.Get(index);
}
inline const ::pb2::ttask& tklink::speech_tasks(int index) const {
  // @@protoc_insertion_point(field_get:pb2.tklink.speech_tasks)
  return _internal_speech_tasks(index);
}
inline ::pb2::ttask* tklink::_internal_add_speech_tasks() {
  return _impl_.speech_tasks_.Add();
}
inline ::pb2::ttask* tklink::add_speech_tasks() {
  ::pb2::ttask* _add = _internal_add_speech_tasks();
  // @@protoc_insertion_point(field_add:pb2.tklink.speech_tasks)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >&
tklink::speech_tasks() const {
  // @@protoc_insertion_point(field_list:pb2.tklink.speech_tasks)
  return _impl_.speech_tasks_;
}

// repeated .pb2.ttask var_tasks = 6;
inline int tklink::_internal_var_tasks_size() const {
  return _impl_.var_tasks_.size();
}
inline int tklink::var_tasks_size() const {
  return _internal_var_tasks_size();
}
inline void tklink::clear_var_tasks() {
  _impl_.var_tasks_.Clear();
}
inline ::pb2::ttask* tklink::mutable_var_tasks(int index) {
  // @@protoc_insertion_point(field_mutable:pb2.tklink.var_tasks)
  return _impl_.var_tasks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >*
tklink::mutable_var_tasks() {
  // @@protoc_insertion_point(field_mutable_list:pb2.tklink.var_tasks)
  return &_impl_.var_tasks_;
}
inline const ::pb2::ttask& tklink::_internal_var_tasks(int index) const {
  return _impl_.var_tasks_.Get(index);
}
inline const ::pb2::ttask& tklink::var_tasks(int index) const {
  // @@protoc_insertion_point(field_get:pb2.tklink.var_tasks)
  return _internal_var_tasks(index);
}
inline ::pb2::ttask* tklink::_internal_add_var_tasks() {
  return _impl_.var_tasks_.Add();
}
inline ::pb2::ttask* tklink::add_var_tasks() {
  ::pb2::ttask* _add = _internal_add_var_tasks();
  // @@protoc_insertion_point(field_add:pb2.tklink.var_tasks)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >&
tklink::var_tasks() const {
  // @@protoc_insertion_point(field_list:pb2.tklink.var_tasks)
  return _impl_.var_tasks_;
}

// repeated .pb2.ttask timed_tasks = 7;
inline int tklink::_internal_timed_tasks_size() const {
  return _impl_.timed_tasks_.size();
}
inline int tklink::timed_tasks_size() const {
  return _internal_timed_tasks_size();
}
inline void tklink::clear_timed_tasks() {
  _impl_.timed_tasks_.Clear();
}
inline ::pb2::ttask* tklink::mutable_timed_tasks(int index) {
  // @@protoc_insertion_point(field_mutable:pb2.tklink.timed_tasks)
  return _impl_.timed_tasks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >*
tklink::mutable_timed_tasks() {
  // @@protoc_insertion_point(field_mutable_list:pb2.tklink.timed_tasks)
  return &_impl_.timed_tasks_;
}
inline const ::pb2::ttask& tklink::_internal_timed_tasks(int index) const {
  return _impl_.timed_tasks_.Get(index);
}
inline const ::pb2::ttask& tklink::timed_tasks(int index) const {
  // @@protoc_insertion_point(field_get:pb2.tklink.timed_tasks)
  return _internal_timed_tasks(index);
}
inline ::pb2::ttask* tklink::_internal_add_timed_tasks() {
  return _impl_.timed_tasks_.Add();
}
inline ::pb2::ttask* tklink::add_timed_tasks() {
  ::pb2::ttask* _add = _internal_add_timed_tasks();
  // @@protoc_insertion_point(field_add:pb2.tklink.timed_tasks)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::ttask >&
tklink::timed_tasks() const {
  // @@protoc_insertion_point(field_list:pb2.tklink.timed_tasks)
  return _impl_.timed_tasks_;
}

// repeated .pb2.tiot_device iot_devices = 8;
inline int tklink::_internal_iot_devices_size() const {
  return _impl_.iot_devices_.size();
}
inline int tklink::iot_devices_size() const {
  return _internal_iot_devices_size();
}
inline void tklink::clear_iot_devices() {
  _impl_.iot_devices_.Clear();
}
inline ::pb2::tiot_device* tklink::mutable_iot_devices(int index) {
  // @@protoc_insertion_point(field_mutable:pb2.tklink.iot_devices)
  return _impl_.iot_devices_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tiot_device >*
tklink::mutable_iot_devices() {
  // @@protoc_insertion_point(field_mutable_list:pb2.tklink.iot_devices)
  return &_impl_.iot_devices_;
}
inline const ::pb2::tiot_device& tklink::_internal_iot_devices(int index) const {
  return _impl_.iot_devices_.Get(index);
}
inline const ::pb2::tiot_device& tklink::iot_devices(int index) const {
  // @@protoc_insertion_point(field_get:pb2.tklink.iot_devices)
  return _internal_iot_devices(index);
}
inline ::pb2::tiot_device* tklink::_internal_add_iot_devices() {
  return _impl_.iot_devices_.Add();
}
inline ::pb2::tiot_device* tklink::add_iot_devices() {
  ::pb2::tiot_device* _add = _internal_add_iot_devices();
  // @@protoc_insertion_point(field_add:pb2.tklink.iot_devices)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tiot_device >&
tklink::iot_devices() const {
  // @@protoc_insertion_point(field_list:pb2.tklink.iot_devices)
  return _impl_.iot_devices_;
}

// string speech_sensor_cfg = 10;
inline void tklink::clear_speech_sensor_cfg() {
  _impl_.speech_sensor_cfg_.ClearToEmpty();
}
inline const std::string& tklink::speech_sensor_cfg() const {
  // @@protoc_insertion_point(field_get:pb2.tklink.speech_sensor_cfg)
  return _internal_speech_sensor_cfg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tklink::set_speech_sensor_cfg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.speech_sensor_cfg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tklink.speech_sensor_cfg)
}
inline std::string* tklink::mutable_speech_sensor_cfg() {
  std::string* _s = _internal_mutable_speech_sensor_cfg();
  // @@protoc_insertion_point(field_mutable:pb2.tklink.speech_sensor_cfg)
  return _s;
}
inline const std::string& tklink::_internal_speech_sensor_cfg() const {
  return _impl_.speech_sensor_cfg_.Get();
}
inline void tklink::_internal_set_speech_sensor_cfg(const std::string& value) {
  
  _impl_.speech_sensor_cfg_.Set(value, GetArenaForAllocation());
}
inline std::string* tklink::_internal_mutable_speech_sensor_cfg() {
  
  return _impl_.speech_sensor_cfg_.Mutable(GetArenaForAllocation());
}
inline std::string* tklink::release_speech_sensor_cfg() {
  // @@protoc_insertion_point(field_release:pb2.tklink.speech_sensor_cfg)
  return _impl_.speech_sensor_cfg_.Release();
}
inline void tklink::set_allocated_speech_sensor_cfg(std::string* speech_sensor_cfg) {
  if (speech_sensor_cfg != nullptr) {
    
  } else {
    
  }
  _impl_.speech_sensor_cfg_.SetAllocated(speech_sensor_cfg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.speech_sensor_cfg_.IsDefault()) {
    _impl_.speech_sensor_cfg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tklink.speech_sensor_cfg)
}

// string var_sensor_cfg = 11;
inline void tklink::clear_var_sensor_cfg() {
  _impl_.var_sensor_cfg_.ClearToEmpty();
}
inline const std::string& tklink::var_sensor_cfg() const {
  // @@protoc_insertion_point(field_get:pb2.tklink.var_sensor_cfg)
  return _internal_var_sensor_cfg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tklink::set_var_sensor_cfg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.var_sensor_cfg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tklink.var_sensor_cfg)
}
inline std::string* tklink::mutable_var_sensor_cfg() {
  std::string* _s = _internal_mutable_var_sensor_cfg();
  // @@protoc_insertion_point(field_mutable:pb2.tklink.var_sensor_cfg)
  return _s;
}
inline const std::string& tklink::_internal_var_sensor_cfg() const {
  return _impl_.var_sensor_cfg_.Get();
}
inline void tklink::_internal_set_var_sensor_cfg(const std::string& value) {
  
  _impl_.var_sensor_cfg_.Set(value, GetArenaForAllocation());
}
inline std::string* tklink::_internal_mutable_var_sensor_cfg() {
  
  return _impl_.var_sensor_cfg_.Mutable(GetArenaForAllocation());
}
inline std::string* tklink::release_var_sensor_cfg() {
  // @@protoc_insertion_point(field_release:pb2.tklink.var_sensor_cfg)
  return _impl_.var_sensor_cfg_.Release();
}
inline void tklink::set_allocated_var_sensor_cfg(std::string* var_sensor_cfg) {
  if (var_sensor_cfg != nullptr) {
    
  } else {
    
  }
  _impl_.var_sensor_cfg_.SetAllocated(var_sensor_cfg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.var_sensor_cfg_.IsDefault()) {
    _impl_.var_sensor_cfg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tklink.var_sensor_cfg)
}

// string timed_sensor_cfg = 12;
inline void tklink::clear_timed_sensor_cfg() {
  _impl_.timed_sensor_cfg_.ClearToEmpty();
}
inline const std::string& tklink::timed_sensor_cfg() const {
  // @@protoc_insertion_point(field_get:pb2.tklink.timed_sensor_cfg)
  return _internal_timed_sensor_cfg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tklink::set_timed_sensor_cfg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timed_sensor_cfg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tklink.timed_sensor_cfg)
}
inline std::string* tklink::mutable_timed_sensor_cfg() {
  std::string* _s = _internal_mutable_timed_sensor_cfg();
  // @@protoc_insertion_point(field_mutable:pb2.tklink.timed_sensor_cfg)
  return _s;
}
inline const std::string& tklink::_internal_timed_sensor_cfg() const {
  return _impl_.timed_sensor_cfg_.Get();
}
inline void tklink::_internal_set_timed_sensor_cfg(const std::string& value) {
  
  _impl_.timed_sensor_cfg_.Set(value, GetArenaForAllocation());
}
inline std::string* tklink::_internal_mutable_timed_sensor_cfg() {
  
  return _impl_.timed_sensor_cfg_.Mutable(GetArenaForAllocation());
}
inline std::string* tklink::release_timed_sensor_cfg() {
  // @@protoc_insertion_point(field_release:pb2.tklink.timed_sensor_cfg)
  return _impl_.timed_sensor_cfg_.Release();
}
inline void tklink::set_allocated_timed_sensor_cfg(std::string* timed_sensor_cfg) {
  if (timed_sensor_cfg != nullptr) {
    
  } else {
    
  }
  _impl_.timed_sensor_cfg_.SetAllocated(timed_sensor_cfg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timed_sensor_cfg_.IsDefault()) {
    _impl_.timed_sensor_cfg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tklink.timed_sensor_cfg)
}

// string base_scene_cfg = 13;
inline void tklink::clear_base_scene_cfg() {
  _impl_.base_scene_cfg_.ClearToEmpty();
}
inline const std::string& tklink::base_scene_cfg() const {
  // @@protoc_insertion_point(field_get:pb2.tklink.base_scene_cfg)
  return _internal_base_scene_cfg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tklink::set_base_scene_cfg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.base_scene_cfg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tklink.base_scene_cfg)
}
inline std::string* tklink::mutable_base_scene_cfg() {
  std::string* _s = _internal_mutable_base_scene_cfg();
  // @@protoc_insertion_point(field_mutable:pb2.tklink.base_scene_cfg)
  return _s;
}
inline const std::string& tklink::_internal_base_scene_cfg() const {
  return _impl_.base_scene_cfg_.Get();
}
inline void tklink::_internal_set_base_scene_cfg(const std::string& value) {
  
  _impl_.base_scene_cfg_.Set(value, GetArenaForAllocation());
}
inline std::string* tklink::_internal_mutable_base_scene_cfg() {
  
  return _impl_.base_scene_cfg_.Mutable(GetArenaForAllocation());
}
inline std::string* tklink::release_base_scene_cfg() {
  // @@protoc_insertion_point(field_release:pb2.tklink.base_scene_cfg)
  return _impl_.base_scene_cfg_.Release();
}
inline void tklink::set_allocated_base_scene_cfg(std::string* base_scene_cfg) {
  if (base_scene_cfg != nullptr) {
    
  } else {
    
  }
  _impl_.base_scene_cfg_.SetAllocated(base_scene_cfg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.base_scene_cfg_.IsDefault()) {
    _impl_.base_scene_cfg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tklink.base_scene_cfg)
}

// string task_cpp_cfg = 14;
inline void tklink::clear_task_cpp_cfg() {
  _impl_.task_cpp_cfg_.ClearToEmpty();
}
inline const std::string& tklink::task_cpp_cfg() const {
  // @@protoc_insertion_point(field_get:pb2.tklink.task_cpp_cfg)
  return _internal_task_cpp_cfg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tklink::set_task_cpp_cfg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.task_cpp_cfg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tklink.task_cpp_cfg)
}
inline std::string* tklink::mutable_task_cpp_cfg() {
  std::string* _s = _internal_mutable_task_cpp_cfg();
  // @@protoc_insertion_point(field_mutable:pb2.tklink.task_cpp_cfg)
  return _s;
}
inline const std::string& tklink::_internal_task_cpp_cfg() const {
  return _impl_.task_cpp_cfg_.Get();
}
inline void tklink::_internal_set_task_cpp_cfg(const std::string& value) {
  
  _impl_.task_cpp_cfg_.Set(value, GetArenaForAllocation());
}
inline std::string* tklink::_internal_mutable_task_cpp_cfg() {
  
  return _impl_.task_cpp_cfg_.Mutable(GetArenaForAllocation());
}
inline std::string* tklink::release_task_cpp_cfg() {
  // @@protoc_insertion_point(field_release:pb2.tklink.task_cpp_cfg)
  return _impl_.task_cpp_cfg_.Release();
}
inline void tklink::set_allocated_task_cpp_cfg(std::string* task_cpp_cfg) {
  if (task_cpp_cfg != nullptr) {
    
  } else {
    
  }
  _impl_.task_cpp_cfg_.SetAllocated(task_cpp_cfg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.task_cpp_cfg_.IsDefault()) {
    _impl_.task_cpp_cfg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tklink.task_cpp_cfg)
}

// string add_timed_task_cfg = 16;
inline void tklink::clear_add_timed_task_cfg() {
  _impl_.add_timed_task_cfg_.ClearToEmpty();
}
inline const std::string& tklink::add_timed_task_cfg() const {
  // @@protoc_insertion_point(field_get:pb2.tklink.add_timed_task_cfg)
  return _internal_add_timed_task_cfg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tklink::set_add_timed_task_cfg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.add_timed_task_cfg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tklink.add_timed_task_cfg)
}
inline std::string* tklink::mutable_add_timed_task_cfg() {
  std::string* _s = _internal_mutable_add_timed_task_cfg();
  // @@protoc_insertion_point(field_mutable:pb2.tklink.add_timed_task_cfg)
  return _s;
}
inline const std::string& tklink::_internal_add_timed_task_cfg() const {
  return _impl_.add_timed_task_cfg_.Get();
}
inline void tklink::_internal_set_add_timed_task_cfg(const std::string& value) {
  
  _impl_.add_timed_task_cfg_.Set(value, GetArenaForAllocation());
}
inline std::string* tklink::_internal_mutable_add_timed_task_cfg() {
  
  return _impl_.add_timed_task_cfg_.Mutable(GetArenaForAllocation());
}
inline std::string* tklink::release_add_timed_task_cfg() {
  // @@protoc_insertion_point(field_release:pb2.tklink.add_timed_task_cfg)
  return _impl_.add_timed_task_cfg_.Release();
}
inline void tklink::set_allocated_add_timed_task_cfg(std::string* add_timed_task_cfg) {
  if (add_timed_task_cfg != nullptr) {
    
  } else {
    
  }
  _impl_.add_timed_task_cfg_.SetAllocated(add_timed_task_cfg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.add_timed_task_cfg_.IsDefault()) {
    _impl_.add_timed_task_cfg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tklink.add_timed_task_cfg)
}

// string courselist_cfg = 17;
inline void tklink::clear_courselist_cfg() {
  _impl_.courselist_cfg_.ClearToEmpty();
}
inline const std::string& tklink::courselist_cfg() const {
  // @@protoc_insertion_point(field_get:pb2.tklink.courselist_cfg)
  return _internal_courselist_cfg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tklink::set_courselist_cfg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.courselist_cfg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tklink.courselist_cfg)
}
inline std::string* tklink::mutable_courselist_cfg() {
  std::string* _s = _internal_mutable_courselist_cfg();
  // @@protoc_insertion_point(field_mutable:pb2.tklink.courselist_cfg)
  return _s;
}
inline const std::string& tklink::_internal_courselist_cfg() const {
  return _impl_.courselist_cfg_.Get();
}
inline void tklink::_internal_set_courselist_cfg(const std::string& value) {
  
  _impl_.courselist_cfg_.Set(value, GetArenaForAllocation());
}
inline std::string* tklink::_internal_mutable_courselist_cfg() {
  
  return _impl_.courselist_cfg_.Mutable(GetArenaForAllocation());
}
inline std::string* tklink::release_courselist_cfg() {
  // @@protoc_insertion_point(field_release:pb2.tklink.courselist_cfg)
  return _impl_.courselist_cfg_.Release();
}
inline void tklink::set_allocated_courselist_cfg(std::string* courselist_cfg) {
  if (courselist_cfg != nullptr) {
    
  } else {
    
  }
  _impl_.courselist_cfg_.SetAllocated(courselist_cfg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.courselist_cfg_.IsDefault()) {
    _impl_.courselist_cfg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tklink.courselist_cfg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb2

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_klink_2eproto
