// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_logs_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_logs_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_logs_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_logs_2eproto {
  static const uint32_t offsets[];
};
namespace pb2 {
class tlog;
struct tlogDefaultTypeInternal;
extern tlogDefaultTypeInternal _tlog_default_instance_;
class tlogs;
struct tlogsDefaultTypeInternal;
extern tlogsDefaultTypeInternal _tlogs_default_instance_;
}  // namespace pb2
PROTOBUF_NAMESPACE_OPEN
template<> ::pb2::tlog* Arena::CreateMaybeMessage<::pb2::tlog>(Arena*);
template<> ::pb2::tlogs* Arena::CreateMaybeMessage<::pb2::tlogs>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb2 {

// ===================================================================

class tlog final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pb2.tlog) */ {
 public:
  inline tlog() : tlog(nullptr) {}
  ~tlog() override;
  explicit PROTOBUF_CONSTEXPR tlog(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  tlog(const tlog& from);
  tlog(tlog&& from) noexcept
    : tlog() {
    *this = ::std::move(from);
  }

  inline tlog& operator=(const tlog& from) {
    CopyFrom(from);
    return *this;
  }
  inline tlog& operator=(tlog&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const tlog& default_instance() {
    return *internal_default_instance();
  }
  static inline const tlog* internal_default_instance() {
    return reinterpret_cast<const tlog*>(
               &_tlog_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(tlog& a, tlog& b) {
    a.Swap(&b);
  }
  inline void Swap(tlog* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(tlog* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  tlog* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<tlog>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const tlog& from);
  void MergeFrom(const tlog& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(tlog* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb2.tlog";
  }
  protected:
  explicit tlog(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApltIdFieldNumber = 4,
    kTaskIdFieldNumber = 5,
    kDeviceIdFieldNumber = 6,
    kMsgFieldNumber = 7,
    kTimestampFieldNumber = 1,
    kTypeFieldNumber = 2,
    kAiagentFieldNumber = 10,
    kTokensFieldNumber = 8,
  };
  // string aplt_id = 4;
  void clear_aplt_id();
  const std::string& aplt_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_aplt_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_aplt_id();
  PROTOBUF_NODISCARD std::string* release_aplt_id();
  void set_allocated_aplt_id(std::string* aplt_id);
  private:
  const std::string& _internal_aplt_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_aplt_id(const std::string& value);
  std::string* _internal_mutable_aplt_id();
  public:

  // string task_id = 5;
  void clear_task_id();
  const std::string& task_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_task_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_task_id();
  PROTOBUF_NODISCARD std::string* release_task_id();
  void set_allocated_task_id(std::string* task_id);
  private:
  const std::string& _internal_task_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_task_id(const std::string& value);
  std::string* _internal_mutable_task_id();
  public:

  // string device_id = 6;
  void clear_device_id();
  const std::string& device_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_device_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_device_id();
  PROTOBUF_NODISCARD std::string* release_device_id();
  void set_allocated_device_id(std::string* device_id);
  private:
  const std::string& _internal_device_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_device_id(const std::string& value);
  std::string* _internal_mutable_device_id();
  public:

  // string msg = 7;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // int64 timestamp = 1;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // int32 type = 2;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // bool aiagent = 10;
  void clear_aiagent();
  bool aiagent() const;
  void set_aiagent(bool value);
  private:
  bool _internal_aiagent() const;
  void _internal_set_aiagent(bool value);
  public:

  // uint64 tokens = 8;
  void clear_tokens();
  uint64_t tokens() const;
  void set_tokens(uint64_t value);
  private:
  uint64_t _internal_tokens() const;
  void _internal_set_tokens(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb2.tlog)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr aplt_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    int64_t timestamp_;
    int32_t type_;
    bool aiagent_;
    uint64_t tokens_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_logs_2eproto;
};
// -------------------------------------------------------------------

class tlogs final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pb2.tlogs) */ {
 public:
  inline tlogs() : tlogs(nullptr) {}
  ~tlogs() override;
  explicit PROTOBUF_CONSTEXPR tlogs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  tlogs(const tlogs& from);
  tlogs(tlogs&& from) noexcept
    : tlogs() {
    *this = ::std::move(from);
  }

  inline tlogs& operator=(const tlogs& from) {
    CopyFrom(from);
    return *this;
  }
  inline tlogs& operator=(tlogs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const tlogs& default_instance() {
    return *internal_default_instance();
  }
  static inline const tlogs* internal_default_instance() {
    return reinterpret_cast<const tlogs*>(
               &_tlogs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(tlogs& a, tlogs& b) {
    a.Swap(&b);
  }
  inline void Swap(tlogs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(tlogs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  tlogs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<tlogs>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const tlogs& from);
  void MergeFrom(const tlogs& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(tlogs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb2.tlogs";
  }
  protected:
  explicit tlogs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogsFieldNumber = 3,
    kVersionFieldNumber = 1,
  };
  // repeated .pb2.tlog logs = 3;
  int logs_size() const;
  private:
  int _internal_logs_size() const;
  public:
  void clear_logs();
  ::pb2::tlog* mutable_logs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tlog >*
      mutable_logs();
  private:
  const ::pb2::tlog& _internal_logs(int index) const;
  ::pb2::tlog* _internal_add_logs();
  public:
  const ::pb2::tlog& logs(int index) const;
  ::pb2::tlog* add_logs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tlog >&
      logs() const;

  // int32 version = 1;
  void clear_version();
  int32_t version() const;
  void set_version(int32_t value);
  private:
  int32_t _internal_version() const;
  void _internal_set_version(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb2.tlogs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tlog > logs_;
    int32_t version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_logs_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// tlog

// int64 timestamp = 1;
inline void tlog::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t tlog::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t tlog::timestamp() const {
  // @@protoc_insertion_point(field_get:pb2.tlog.timestamp)
  return _internal_timestamp();
}
inline void tlog::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void tlog::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:pb2.tlog.timestamp)
}

// int32 type = 2;
inline void tlog::clear_type() {
  _impl_.type_ = 0;
}
inline int32_t tlog::_internal_type() const {
  return _impl_.type_;
}
inline int32_t tlog::type() const {
  // @@protoc_insertion_point(field_get:pb2.tlog.type)
  return _internal_type();
}
inline void tlog::_internal_set_type(int32_t value) {
  
  _impl_.type_ = value;
}
inline void tlog::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:pb2.tlog.type)
}

// string aplt_id = 4;
inline void tlog::clear_aplt_id() {
  _impl_.aplt_id_.ClearToEmpty();
}
inline const std::string& tlog::aplt_id() const {
  // @@protoc_insertion_point(field_get:pb2.tlog.aplt_id)
  return _internal_aplt_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tlog::set_aplt_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.aplt_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tlog.aplt_id)
}
inline std::string* tlog::mutable_aplt_id() {
  std::string* _s = _internal_mutable_aplt_id();
  // @@protoc_insertion_point(field_mutable:pb2.tlog.aplt_id)
  return _s;
}
inline const std::string& tlog::_internal_aplt_id() const {
  return _impl_.aplt_id_.Get();
}
inline void tlog::_internal_set_aplt_id(const std::string& value) {
  
  _impl_.aplt_id_.Set(value, GetArenaForAllocation());
}
inline std::string* tlog::_internal_mutable_aplt_id() {
  
  return _impl_.aplt_id_.Mutable(GetArenaForAllocation());
}
inline std::string* tlog::release_aplt_id() {
  // @@protoc_insertion_point(field_release:pb2.tlog.aplt_id)
  return _impl_.aplt_id_.Release();
}
inline void tlog::set_allocated_aplt_id(std::string* aplt_id) {
  if (aplt_id != nullptr) {
    
  } else {
    
  }
  _impl_.aplt_id_.SetAllocated(aplt_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.aplt_id_.IsDefault()) {
    _impl_.aplt_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tlog.aplt_id)
}

// string task_id = 5;
inline void tlog::clear_task_id() {
  _impl_.task_id_.ClearToEmpty();
}
inline const std::string& tlog::task_id() const {
  // @@protoc_insertion_point(field_get:pb2.tlog.task_id)
  return _internal_task_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tlog::set_task_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.task_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tlog.task_id)
}
inline std::string* tlog::mutable_task_id() {
  std::string* _s = _internal_mutable_task_id();
  // @@protoc_insertion_point(field_mutable:pb2.tlog.task_id)
  return _s;
}
inline const std::string& tlog::_internal_task_id() const {
  return _impl_.task_id_.Get();
}
inline void tlog::_internal_set_task_id(const std::string& value) {
  
  _impl_.task_id_.Set(value, GetArenaForAllocation());
}
inline std::string* tlog::_internal_mutable_task_id() {
  
  return _impl_.task_id_.Mutable(GetArenaForAllocation());
}
inline std::string* tlog::release_task_id() {
  // @@protoc_insertion_point(field_release:pb2.tlog.task_id)
  return _impl_.task_id_.Release();
}
inline void tlog::set_allocated_task_id(std::string* task_id) {
  if (task_id != nullptr) {
    
  } else {
    
  }
  _impl_.task_id_.SetAllocated(task_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.task_id_.IsDefault()) {
    _impl_.task_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tlog.task_id)
}

// string device_id = 6;
inline void tlog::clear_device_id() {
  _impl_.device_id_.ClearToEmpty();
}
inline const std::string& tlog::device_id() const {
  // @@protoc_insertion_point(field_get:pb2.tlog.device_id)
  return _internal_device_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tlog::set_device_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.device_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tlog.device_id)
}
inline std::string* tlog::mutable_device_id() {
  std::string* _s = _internal_mutable_device_id();
  // @@protoc_insertion_point(field_mutable:pb2.tlog.device_id)
  return _s;
}
inline const std::string& tlog::_internal_device_id() const {
  return _impl_.device_id_.Get();
}
inline void tlog::_internal_set_device_id(const std::string& value) {
  
  _impl_.device_id_.Set(value, GetArenaForAllocation());
}
inline std::string* tlog::_internal_mutable_device_id() {
  
  return _impl_.device_id_.Mutable(GetArenaForAllocation());
}
inline std::string* tlog::release_device_id() {
  // @@protoc_insertion_point(field_release:pb2.tlog.device_id)
  return _impl_.device_id_.Release();
}
inline void tlog::set_allocated_device_id(std::string* device_id) {
  if (device_id != nullptr) {
    
  } else {
    
  }
  _impl_.device_id_.SetAllocated(device_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.device_id_.IsDefault()) {
    _impl_.device_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tlog.device_id)
}

// string msg = 7;
inline void tlog::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& tlog::msg() const {
  // @@protoc_insertion_point(field_get:pb2.tlog.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void tlog::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.tlog.msg)
}
inline std::string* tlog::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:pb2.tlog.msg)
  return _s;
}
inline const std::string& tlog::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void tlog::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* tlog::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* tlog::release_msg() {
  // @@protoc_insertion_point(field_release:pb2.tlog.msg)
  return _impl_.msg_.Release();
}
inline void tlog::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.tlog.msg)
}

// uint64 tokens = 8;
inline void tlog::clear_tokens() {
  _impl_.tokens_ = uint64_t{0u};
}
inline uint64_t tlog::_internal_tokens() const {
  return _impl_.tokens_;
}
inline uint64_t tlog::tokens() const {
  // @@protoc_insertion_point(field_get:pb2.tlog.tokens)
  return _internal_tokens();
}
inline void tlog::_internal_set_tokens(uint64_t value) {
  
  _impl_.tokens_ = value;
}
inline void tlog::set_tokens(uint64_t value) {
  _internal_set_tokens(value);
  // @@protoc_insertion_point(field_set:pb2.tlog.tokens)
}

// bool aiagent = 10;
inline void tlog::clear_aiagent() {
  _impl_.aiagent_ = false;
}
inline bool tlog::_internal_aiagent() const {
  return _impl_.aiagent_;
}
inline bool tlog::aiagent() const {
  // @@protoc_insertion_point(field_get:pb2.tlog.aiagent)
  return _internal_aiagent();
}
inline void tlog::_internal_set_aiagent(bool value) {
  
  _impl_.aiagent_ = value;
}
inline void tlog::set_aiagent(bool value) {
  _internal_set_aiagent(value);
  // @@protoc_insertion_point(field_set:pb2.tlog.aiagent)
}

// -------------------------------------------------------------------

// tlogs

// int32 version = 1;
inline void tlogs::clear_version() {
  _impl_.version_ = 0;
}
inline int32_t tlogs::_internal_version() const {
  return _impl_.version_;
}
inline int32_t tlogs::version() const {
  // @@protoc_insertion_point(field_get:pb2.tlogs.version)
  return _internal_version();
}
inline void tlogs::_internal_set_version(int32_t value) {
  
  _impl_.version_ = value;
}
inline void tlogs::set_version(int32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:pb2.tlogs.version)
}

// repeated .pb2.tlog logs = 3;
inline int tlogs::_internal_logs_size() const {
  return _impl_.logs_.size();
}
inline int tlogs::logs_size() const {
  return _internal_logs_size();
}
inline void tlogs::clear_logs() {
  _impl_.logs_.Clear();
}
inline ::pb2::tlog* tlogs::mutable_logs(int index) {
  // @@protoc_insertion_point(field_mutable:pb2.tlogs.logs)
  return _impl_.logs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tlog >*
tlogs::mutable_logs() {
  // @@protoc_insertion_point(field_mutable_list:pb2.tlogs.logs)
  return &_impl_.logs_;
}
inline const ::pb2::tlog& tlogs::_internal_logs(int index) const {
  return _impl_.logs_.Get(index);
}
inline const ::pb2::tlog& tlogs::logs(int index) const {
  // @@protoc_insertion_point(field_get:pb2.tlogs.logs)
  return _internal_logs(index);
}
inline ::pb2::tlog* tlogs::_internal_add_logs() {
  return _impl_.logs_.Add();
}
inline ::pb2::tlog* tlogs::add_logs() {
  ::pb2::tlog* _add = _internal_add_logs();
  // @@protoc_insertion_point(field_add:pb2.tlogs.logs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::tlog >&
tlogs::logs() const {
  // @@protoc_insertion_point(field_list:pb2.tlogs.logs)
  return _impl_.logs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb2

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_logs_2eproto
