// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lprotobuf.proto

#include "lprotobuf.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb2 {
PROTOBUF_CONSTEXPR titem::titem(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.stritem0_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stritem1_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stritem2_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stritem3_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stritem4_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.n64item0_)*/int64_t{0}
  , /*decltype(_impl_.n32item0_)*/0
  , /*decltype(_impl_.n32item1_)*/0
  , /*decltype(_impl_.n64item1_)*/int64_t{0}
  , /*decltype(_impl_.n64item2_)*/int64_t{0}
  , /*decltype(_impl_.n32item2_)*/0
  , /*decltype(_impl_.n32item3_)*/0
  , /*decltype(_impl_.n32item4_)*/0
  , /*decltype(_impl_.n32item5_)*/0
  , /*decltype(_impl_.n32item6_)*/0
  , /*decltype(_impl_.n32item7_)*/0
  , /*decltype(_impl_.n32item8_)*/0
  , /*decltype(_impl_.n32item9_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct titemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR titemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~titemDefaultTypeInternal() {}
  union {
    titem _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 titemDefaultTypeInternal _titem_default_instance_;
PROTOBUF_CONSTEXPR titems::titems(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.items_)*/{}
  , /*decltype(_impl_.strtop0_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.strtop1_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.strtop2_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.n64top0_)*/int64_t{0}
  , /*decltype(_impl_.n32top0_)*/0
  , /*decltype(_impl_.n32top1_)*/0
  , /*decltype(_impl_.n64top1_)*/int64_t{0}
  , /*decltype(_impl_.n64top2_)*/int64_t{0}
  , /*decltype(_impl_.n32top2_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct titemsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR titemsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~titemsDefaultTypeInternal() {}
  union {
    titems _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 titemsDefaultTypeInternal _titems_default_instance_;
}  // namespace pb2
namespace pb2 {

// ===================================================================

class titem::_Internal {
 public:
};

titem::titem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb2.titem)
}
titem::titem(const titem& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  titem* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.stritem0_){}
    , decltype(_impl_.stritem1_){}
    , decltype(_impl_.stritem2_){}
    , decltype(_impl_.stritem3_){}
    , decltype(_impl_.stritem4_){}
    , decltype(_impl_.n64item0_){}
    , decltype(_impl_.n32item0_){}
    , decltype(_impl_.n32item1_){}
    , decltype(_impl_.n64item1_){}
    , decltype(_impl_.n64item2_){}
    , decltype(_impl_.n32item2_){}
    , decltype(_impl_.n32item3_){}
    , decltype(_impl_.n32item4_){}
    , decltype(_impl_.n32item5_){}
    , decltype(_impl_.n32item6_){}
    , decltype(_impl_.n32item7_){}
    , decltype(_impl_.n32item8_){}
    , decltype(_impl_.n32item9_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.stritem0_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem0_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_stritem0().empty()) {
    _this->_impl_.stritem0_.Set(from._internal_stritem0(), 
      _this->GetArenaForAllocation());
  }
  _impl_.stritem1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_stritem1().empty()) {
    _this->_impl_.stritem1_.Set(from._internal_stritem1(), 
      _this->GetArenaForAllocation());
  }
  _impl_.stritem2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_stritem2().empty()) {
    _this->_impl_.stritem2_.Set(from._internal_stritem2(), 
      _this->GetArenaForAllocation());
  }
  _impl_.stritem3_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem3_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_stritem3().empty()) {
    _this->_impl_.stritem3_.Set(from._internal_stritem3(), 
      _this->GetArenaForAllocation());
  }
  _impl_.stritem4_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem4_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_stritem4().empty()) {
    _this->_impl_.stritem4_.Set(from._internal_stritem4(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.n64item0_, &from._impl_.n64item0_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.n32item9_) -
    reinterpret_cast<char*>(&_impl_.n64item0_)) + sizeof(_impl_.n32item9_));
  // @@protoc_insertion_point(copy_constructor:pb2.titem)
}

inline void titem::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.stritem0_){}
    , decltype(_impl_.stritem1_){}
    , decltype(_impl_.stritem2_){}
    , decltype(_impl_.stritem3_){}
    , decltype(_impl_.stritem4_){}
    , decltype(_impl_.n64item0_){int64_t{0}}
    , decltype(_impl_.n32item0_){0}
    , decltype(_impl_.n32item1_){0}
    , decltype(_impl_.n64item1_){int64_t{0}}
    , decltype(_impl_.n64item2_){int64_t{0}}
    , decltype(_impl_.n32item2_){0}
    , decltype(_impl_.n32item3_){0}
    , decltype(_impl_.n32item4_){0}
    , decltype(_impl_.n32item5_){0}
    , decltype(_impl_.n32item6_){0}
    , decltype(_impl_.n32item7_){0}
    , decltype(_impl_.n32item8_){0}
    , decltype(_impl_.n32item9_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.stritem0_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem0_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.stritem1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.stritem2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.stritem3_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem3_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.stritem4_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stritem4_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

titem::~titem() {
  // @@protoc_insertion_point(destructor:pb2.titem)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void titem::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.stritem0_.Destroy();
  _impl_.stritem1_.Destroy();
  _impl_.stritem2_.Destroy();
  _impl_.stritem3_.Destroy();
  _impl_.stritem4_.Destroy();
}

void titem::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void titem::Clear() {
// @@protoc_insertion_point(message_clear_start:pb2.titem)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stritem0_.ClearToEmpty();
  _impl_.stritem1_.ClearToEmpty();
  _impl_.stritem2_.ClearToEmpty();
  _impl_.stritem3_.ClearToEmpty();
  _impl_.stritem4_.ClearToEmpty();
  ::memset(&_impl_.n64item0_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.n32item9_) -
      reinterpret_cast<char*>(&_impl_.n64item0_)) + sizeof(_impl_.n32item9_));
  _internal_metadata_.Clear<std::string>();
}

const char* titem::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 n32item0 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.n32item0_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 n64item0 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.n64item0_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string stritem0 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_stritem0();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 n32item1 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.n32item1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 n64item1 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.n64item1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string stritem1 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_stritem1();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 n32item2 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.n32item2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 n64item2 = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.n64item2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string stritem2 = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_stritem2();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 n32item3 = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.n32item3_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string stritem3 = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_stritem3();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 n32item4 = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _impl_.n32item4_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string stritem4 = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_stritem4();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 n32item5 = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 112)) {
          _impl_.n32item5_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 n32item6 = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 120)) {
          _impl_.n32item6_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 n32item7 = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 128)) {
          _impl_.n32item7_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 n32item8 = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 136)) {
          _impl_.n32item8_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 n32item9 = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 144)) {
          _impl_.n32item9_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* titem::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb2.titem)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 n32item0 = 1;
  if (this->_internal_n32item0() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_n32item0(), target);
  }

  // int64 n64item0 = 2;
  if (this->_internal_n64item0() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_n64item0(), target);
  }

  // string stritem0 = 3;
  if (!this->_internal_stritem0().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_stritem0().data(), static_cast<int>(this->_internal_stritem0().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.titem.stritem0");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_stritem0(), target);
  }

  // int32 n32item1 = 4;
  if (this->_internal_n32item1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_n32item1(), target);
  }

  // int64 n64item1 = 5;
  if (this->_internal_n64item1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_n64item1(), target);
  }

  // string stritem1 = 6;
  if (!this->_internal_stritem1().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_stritem1().data(), static_cast<int>(this->_internal_stritem1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.titem.stritem1");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_stritem1(), target);
  }

  // int32 n32item2 = 7;
  if (this->_internal_n32item2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_n32item2(), target);
  }

  // int64 n64item2 = 8;
  if (this->_internal_n64item2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(8, this->_internal_n64item2(), target);
  }

  // string stritem2 = 9;
  if (!this->_internal_stritem2().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_stritem2().data(), static_cast<int>(this->_internal_stritem2().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.titem.stritem2");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_stritem2(), target);
  }

  // int32 n32item3 = 10;
  if (this->_internal_n32item3() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_n32item3(), target);
  }

  // string stritem3 = 11;
  if (!this->_internal_stritem3().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_stritem3().data(), static_cast<int>(this->_internal_stritem3().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.titem.stritem3");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_stritem3(), target);
  }

  // int32 n32item4 = 12;
  if (this->_internal_n32item4() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(12, this->_internal_n32item4(), target);
  }

  // string stritem4 = 13;
  if (!this->_internal_stritem4().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_stritem4().data(), static_cast<int>(this->_internal_stritem4().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.titem.stritem4");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_stritem4(), target);
  }

  // int32 n32item5 = 14;
  if (this->_internal_n32item5() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(14, this->_internal_n32item5(), target);
  }

  // int32 n32item6 = 15;
  if (this->_internal_n32item6() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(15, this->_internal_n32item6(), target);
  }

  // int32 n32item7 = 16;
  if (this->_internal_n32item7() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(16, this->_internal_n32item7(), target);
  }

  // int32 n32item8 = 17;
  if (this->_internal_n32item8() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(17, this->_internal_n32item8(), target);
  }

  // int32 n32item9 = 18;
  if (this->_internal_n32item9() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(18, this->_internal_n32item9(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb2.titem)
  return target;
}

size_t titem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb2.titem)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string stritem0 = 3;
  if (!this->_internal_stritem0().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_stritem0());
  }

  // string stritem1 = 6;
  if (!this->_internal_stritem1().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_stritem1());
  }

  // string stritem2 = 9;
  if (!this->_internal_stritem2().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_stritem2());
  }

  // string stritem3 = 11;
  if (!this->_internal_stritem3().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_stritem3());
  }

  // string stritem4 = 13;
  if (!this->_internal_stritem4().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_stritem4());
  }

  // int64 n64item0 = 2;
  if (this->_internal_n64item0() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_n64item0());
  }

  // int32 n32item0 = 1;
  if (this->_internal_n32item0() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32item0());
  }

  // int32 n32item1 = 4;
  if (this->_internal_n32item1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32item1());
  }

  // int64 n64item1 = 5;
  if (this->_internal_n64item1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_n64item1());
  }

  // int64 n64item2 = 8;
  if (this->_internal_n64item2() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_n64item2());
  }

  // int32 n32item2 = 7;
  if (this->_internal_n32item2() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32item2());
  }

  // int32 n32item3 = 10;
  if (this->_internal_n32item3() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32item3());
  }

  // int32 n32item4 = 12;
  if (this->_internal_n32item4() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32item4());
  }

  // int32 n32item5 = 14;
  if (this->_internal_n32item5() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32item5());
  }

  // int32 n32item6 = 15;
  if (this->_internal_n32item6() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32item6());
  }

  // int32 n32item7 = 16;
  if (this->_internal_n32item7() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_n32item7());
  }

  // int32 n32item8 = 17;
  if (this->_internal_n32item8() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_n32item8());
  }

  // int32 n32item9 = 18;
  if (this->_internal_n32item9() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_n32item9());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void titem::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const titem*>(
      &from));
}

void titem::MergeFrom(const titem& from) {
  titem* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:pb2.titem)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_stritem0().empty()) {
    _this->_internal_set_stritem0(from._internal_stritem0());
  }
  if (!from._internal_stritem1().empty()) {
    _this->_internal_set_stritem1(from._internal_stritem1());
  }
  if (!from._internal_stritem2().empty()) {
    _this->_internal_set_stritem2(from._internal_stritem2());
  }
  if (!from._internal_stritem3().empty()) {
    _this->_internal_set_stritem3(from._internal_stritem3());
  }
  if (!from._internal_stritem4().empty()) {
    _this->_internal_set_stritem4(from._internal_stritem4());
  }
  if (from._internal_n64item0() != 0) {
    _this->_internal_set_n64item0(from._internal_n64item0());
  }
  if (from._internal_n32item0() != 0) {
    _this->_internal_set_n32item0(from._internal_n32item0());
  }
  if (from._internal_n32item1() != 0) {
    _this->_internal_set_n32item1(from._internal_n32item1());
  }
  if (from._internal_n64item1() != 0) {
    _this->_internal_set_n64item1(from._internal_n64item1());
  }
  if (from._internal_n64item2() != 0) {
    _this->_internal_set_n64item2(from._internal_n64item2());
  }
  if (from._internal_n32item2() != 0) {
    _this->_internal_set_n32item2(from._internal_n32item2());
  }
  if (from._internal_n32item3() != 0) {
    _this->_internal_set_n32item3(from._internal_n32item3());
  }
  if (from._internal_n32item4() != 0) {
    _this->_internal_set_n32item4(from._internal_n32item4());
  }
  if (from._internal_n32item5() != 0) {
    _this->_internal_set_n32item5(from._internal_n32item5());
  }
  if (from._internal_n32item6() != 0) {
    _this->_internal_set_n32item6(from._internal_n32item6());
  }
  if (from._internal_n32item7() != 0) {
    _this->_internal_set_n32item7(from._internal_n32item7());
  }
  if (from._internal_n32item8() != 0) {
    _this->_internal_set_n32item8(from._internal_n32item8());
  }
  if (from._internal_n32item9() != 0) {
    _this->_internal_set_n32item9(from._internal_n32item9());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void titem::CopyFrom(const titem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb2.titem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool titem::IsInitialized() const {
  return true;
}

void titem::InternalSwap(titem* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.stritem0_, lhs_arena,
      &other->_impl_.stritem0_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.stritem1_, lhs_arena,
      &other->_impl_.stritem1_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.stritem2_, lhs_arena,
      &other->_impl_.stritem2_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.stritem3_, lhs_arena,
      &other->_impl_.stritem3_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.stritem4_, lhs_arena,
      &other->_impl_.stritem4_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(titem, _impl_.n32item9_)
      + sizeof(titem::_impl_.n32item9_)
      - PROTOBUF_FIELD_OFFSET(titem, _impl_.n64item0_)>(
          reinterpret_cast<char*>(&_impl_.n64item0_),
          reinterpret_cast<char*>(&other->_impl_.n64item0_));
}

std::string titem::GetTypeName() const {
  return "pb2.titem";
}


// ===================================================================

class titems::_Internal {
 public:
};

titems::titems(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb2.titems)
}
titems::titems(const titems& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  titems* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){from._impl_.items_}
    , decltype(_impl_.strtop0_){}
    , decltype(_impl_.strtop1_){}
    , decltype(_impl_.strtop2_){}
    , decltype(_impl_.n64top0_){}
    , decltype(_impl_.n32top0_){}
    , decltype(_impl_.n32top1_){}
    , decltype(_impl_.n64top1_){}
    , decltype(_impl_.n64top2_){}
    , decltype(_impl_.n32top2_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.strtop0_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.strtop0_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_strtop0().empty()) {
    _this->_impl_.strtop0_.Set(from._internal_strtop0(), 
      _this->GetArenaForAllocation());
  }
  _impl_.strtop1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.strtop1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_strtop1().empty()) {
    _this->_impl_.strtop1_.Set(from._internal_strtop1(), 
      _this->GetArenaForAllocation());
  }
  _impl_.strtop2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.strtop2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_strtop2().empty()) {
    _this->_impl_.strtop2_.Set(from._internal_strtop2(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.n64top0_, &from._impl_.n64top0_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.n32top2_) -
    reinterpret_cast<char*>(&_impl_.n64top0_)) + sizeof(_impl_.n32top2_));
  // @@protoc_insertion_point(copy_constructor:pb2.titems)
}

inline void titems::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.items_){arena}
    , decltype(_impl_.strtop0_){}
    , decltype(_impl_.strtop1_){}
    , decltype(_impl_.strtop2_){}
    , decltype(_impl_.n64top0_){int64_t{0}}
    , decltype(_impl_.n32top0_){0}
    , decltype(_impl_.n32top1_){0}
    , decltype(_impl_.n64top1_){int64_t{0}}
    , decltype(_impl_.n64top2_){int64_t{0}}
    , decltype(_impl_.n32top2_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.strtop0_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.strtop0_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.strtop1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.strtop1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.strtop2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.strtop2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

titems::~titems() {
  // @@protoc_insertion_point(destructor:pb2.titems)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void titems::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.items_.~RepeatedPtrField();
  _impl_.strtop0_.Destroy();
  _impl_.strtop1_.Destroy();
  _impl_.strtop2_.Destroy();
}

void titems::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void titems::Clear() {
// @@protoc_insertion_point(message_clear_start:pb2.titems)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  _impl_.strtop0_.ClearToEmpty();
  _impl_.strtop1_.ClearToEmpty();
  _impl_.strtop2_.ClearToEmpty();
  ::memset(&_impl_.n64top0_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.n32top2_) -
      reinterpret_cast<char*>(&_impl_.n64top0_)) + sizeof(_impl_.n32top2_));
  _internal_metadata_.Clear<std::string>();
}

const char* titems::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 n32top0 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.n32top0_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 n64top0 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.n64top0_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string strtop0 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_strtop0();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .pb2.titem items = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_items(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 n32top1 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.n32top1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 n64top1 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.n64top1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string strtop1 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_strtop1();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 n32top2 = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.n32top2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 n64top2 = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.n64top2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string strtop2 = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_strtop2();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* titems::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb2.titems)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 n32top0 = 1;
  if (this->_internal_n32top0() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_n32top0(), target);
  }

  // int64 n64top0 = 2;
  if (this->_internal_n64top0() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_n64top0(), target);
  }

  // string strtop0 = 3;
  if (!this->_internal_strtop0().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_strtop0().data(), static_cast<int>(this->_internal_strtop0().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.titems.strtop0");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_strtop0(), target);
  }

  // repeated .pb2.titem items = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_items_size()); i < n; i++) {
    const auto& repfield = this->_internal_items(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // int32 n32top1 = 5;
  if (this->_internal_n32top1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_n32top1(), target);
  }

  // int64 n64top1 = 6;
  if (this->_internal_n64top1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_n64top1(), target);
  }

  // string strtop1 = 7;
  if (!this->_internal_strtop1().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_strtop1().data(), static_cast<int>(this->_internal_strtop1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.titems.strtop1");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_strtop1(), target);
  }

  // int32 n32top2 = 8;
  if (this->_internal_n32top2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_n32top2(), target);
  }

  // int64 n64top2 = 9;
  if (this->_internal_n64top2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(9, this->_internal_n64top2(), target);
  }

  // string strtop2 = 10;
  if (!this->_internal_strtop2().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_strtop2().data(), static_cast<int>(this->_internal_strtop2().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb2.titems.strtop2");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_strtop2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb2.titems)
  return target;
}

size_t titems::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb2.titems)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb2.titem items = 4;
  total_size += 1UL * this->_internal_items_size();
  for (const auto& msg : this->_impl_.items_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string strtop0 = 3;
  if (!this->_internal_strtop0().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_strtop0());
  }

  // string strtop1 = 7;
  if (!this->_internal_strtop1().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_strtop1());
  }

  // string strtop2 = 10;
  if (!this->_internal_strtop2().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_strtop2());
  }

  // int64 n64top0 = 2;
  if (this->_internal_n64top0() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_n64top0());
  }

  // int32 n32top0 = 1;
  if (this->_internal_n32top0() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32top0());
  }

  // int32 n32top1 = 5;
  if (this->_internal_n32top1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32top1());
  }

  // int64 n64top1 = 6;
  if (this->_internal_n64top1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_n64top1());
  }

  // int64 n64top2 = 9;
  if (this->_internal_n64top2() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_n64top2());
  }

  // int32 n32top2 = 8;
  if (this->_internal_n32top2() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_n32top2());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void titems::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const titems*>(
      &from));
}

void titems::MergeFrom(const titems& from) {
  titems* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:pb2.titems)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.items_.MergeFrom(from._impl_.items_);
  if (!from._internal_strtop0().empty()) {
    _this->_internal_set_strtop0(from._internal_strtop0());
  }
  if (!from._internal_strtop1().empty()) {
    _this->_internal_set_strtop1(from._internal_strtop1());
  }
  if (!from._internal_strtop2().empty()) {
    _this->_internal_set_strtop2(from._internal_strtop2());
  }
  if (from._internal_n64top0() != 0) {
    _this->_internal_set_n64top0(from._internal_n64top0());
  }
  if (from._internal_n32top0() != 0) {
    _this->_internal_set_n32top0(from._internal_n32top0());
  }
  if (from._internal_n32top1() != 0) {
    _this->_internal_set_n32top1(from._internal_n32top1());
  }
  if (from._internal_n64top1() != 0) {
    _this->_internal_set_n64top1(from._internal_n64top1());
  }
  if (from._internal_n64top2() != 0) {
    _this->_internal_set_n64top2(from._internal_n64top2());
  }
  if (from._internal_n32top2() != 0) {
    _this->_internal_set_n32top2(from._internal_n32top2());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void titems::CopyFrom(const titems& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb2.titems)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool titems::IsInitialized() const {
  return true;
}

void titems::InternalSwap(titems* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.strtop0_, lhs_arena,
      &other->_impl_.strtop0_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.strtop1_, lhs_arena,
      &other->_impl_.strtop1_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.strtop2_, lhs_arena,
      &other->_impl_.strtop2_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(titems, _impl_.n32top2_)
      + sizeof(titems::_impl_.n32top2_)
      - PROTOBUF_FIELD_OFFSET(titems, _impl_.n64top0_)>(
          reinterpret_cast<char*>(&_impl_.n64top0_),
          reinterpret_cast<char*>(&other->_impl_.n64top0_));
}

std::string titems::GetTypeName() const {
  return "pb2.titems";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb2
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb2::titem*
Arena::CreateMaybeMessage< ::pb2::titem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb2::titem >(arena);
}
template<> PROTOBUF_NOINLINE ::pb2::titems*
Arena::CreateMaybeMessage< ::pb2::titems >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb2::titems >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
