// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lprotobuf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_lprotobuf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_lprotobuf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_lprotobuf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_lprotobuf_2eproto {
  static const uint32_t offsets[];
};
namespace pb2 {
class titem;
struct titemDefaultTypeInternal;
extern titemDefaultTypeInternal _titem_default_instance_;
class titems;
struct titemsDefaultTypeInternal;
extern titemsDefaultTypeInternal _titems_default_instance_;
}  // namespace pb2
PROTOBUF_NAMESPACE_OPEN
template<> ::pb2::titem* Arena::CreateMaybeMessage<::pb2::titem>(Arena*);
template<> ::pb2::titems* Arena::CreateMaybeMessage<::pb2::titems>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb2 {

// ===================================================================

class titem final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pb2.titem) */ {
 public:
  inline titem() : titem(nullptr) {}
  ~titem() override;
  explicit PROTOBUF_CONSTEXPR titem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  titem(const titem& from);
  titem(titem&& from) noexcept
    : titem() {
    *this = ::std::move(from);
  }

  inline titem& operator=(const titem& from) {
    CopyFrom(from);
    return *this;
  }
  inline titem& operator=(titem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const titem& default_instance() {
    return *internal_default_instance();
  }
  static inline const titem* internal_default_instance() {
    return reinterpret_cast<const titem*>(
               &_titem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(titem& a, titem& b) {
    a.Swap(&b);
  }
  inline void Swap(titem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(titem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  titem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<titem>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const titem& from);
  void MergeFrom(const titem& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(titem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb2.titem";
  }
  protected:
  explicit titem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStritem0FieldNumber = 3,
    kStritem1FieldNumber = 6,
    kStritem2FieldNumber = 9,
    kStritem3FieldNumber = 11,
    kStritem4FieldNumber = 13,
    kN64Item0FieldNumber = 2,
    kN32Item0FieldNumber = 1,
    kN32Item1FieldNumber = 4,
    kN64Item1FieldNumber = 5,
    kN64Item2FieldNumber = 8,
    kN32Item2FieldNumber = 7,
    kN32Item3FieldNumber = 10,
    kN32Item4FieldNumber = 12,
    kN32Item5FieldNumber = 14,
    kN32Item6FieldNumber = 15,
    kN32Item7FieldNumber = 16,
    kN32Item8FieldNumber = 17,
    kN32Item9FieldNumber = 18,
  };
  // string stritem0 = 3;
  void clear_stritem0();
  const std::string& stritem0() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stritem0(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stritem0();
  PROTOBUF_NODISCARD std::string* release_stritem0();
  void set_allocated_stritem0(std::string* stritem0);
  private:
  const std::string& _internal_stritem0() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stritem0(const std::string& value);
  std::string* _internal_mutable_stritem0();
  public:

  // string stritem1 = 6;
  void clear_stritem1();
  const std::string& stritem1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stritem1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stritem1();
  PROTOBUF_NODISCARD std::string* release_stritem1();
  void set_allocated_stritem1(std::string* stritem1);
  private:
  const std::string& _internal_stritem1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stritem1(const std::string& value);
  std::string* _internal_mutable_stritem1();
  public:

  // string stritem2 = 9;
  void clear_stritem2();
  const std::string& stritem2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stritem2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stritem2();
  PROTOBUF_NODISCARD std::string* release_stritem2();
  void set_allocated_stritem2(std::string* stritem2);
  private:
  const std::string& _internal_stritem2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stritem2(const std::string& value);
  std::string* _internal_mutable_stritem2();
  public:

  // string stritem3 = 11;
  void clear_stritem3();
  const std::string& stritem3() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stritem3(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stritem3();
  PROTOBUF_NODISCARD std::string* release_stritem3();
  void set_allocated_stritem3(std::string* stritem3);
  private:
  const std::string& _internal_stritem3() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stritem3(const std::string& value);
  std::string* _internal_mutable_stritem3();
  public:

  // string stritem4 = 13;
  void clear_stritem4();
  const std::string& stritem4() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stritem4(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stritem4();
  PROTOBUF_NODISCARD std::string* release_stritem4();
  void set_allocated_stritem4(std::string* stritem4);
  private:
  const std::string& _internal_stritem4() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stritem4(const std::string& value);
  std::string* _internal_mutable_stritem4();
  public:

  // int64 n64item0 = 2;
  void clear_n64item0();
  int64_t n64item0() const;
  void set_n64item0(int64_t value);
  private:
  int64_t _internal_n64item0() const;
  void _internal_set_n64item0(int64_t value);
  public:

  // int32 n32item0 = 1;
  void clear_n32item0();
  int32_t n32item0() const;
  void set_n32item0(int32_t value);
  private:
  int32_t _internal_n32item0() const;
  void _internal_set_n32item0(int32_t value);
  public:

  // int32 n32item1 = 4;
  void clear_n32item1();
  int32_t n32item1() const;
  void set_n32item1(int32_t value);
  private:
  int32_t _internal_n32item1() const;
  void _internal_set_n32item1(int32_t value);
  public:

  // int64 n64item1 = 5;
  void clear_n64item1();
  int64_t n64item1() const;
  void set_n64item1(int64_t value);
  private:
  int64_t _internal_n64item1() const;
  void _internal_set_n64item1(int64_t value);
  public:

  // int64 n64item2 = 8;
  void clear_n64item2();
  int64_t n64item2() const;
  void set_n64item2(int64_t value);
  private:
  int64_t _internal_n64item2() const;
  void _internal_set_n64item2(int64_t value);
  public:

  // int32 n32item2 = 7;
  void clear_n32item2();
  int32_t n32item2() const;
  void set_n32item2(int32_t value);
  private:
  int32_t _internal_n32item2() const;
  void _internal_set_n32item2(int32_t value);
  public:

  // int32 n32item3 = 10;
  void clear_n32item3();
  int32_t n32item3() const;
  void set_n32item3(int32_t value);
  private:
  int32_t _internal_n32item3() const;
  void _internal_set_n32item3(int32_t value);
  public:

  // int32 n32item4 = 12;
  void clear_n32item4();
  int32_t n32item4() const;
  void set_n32item4(int32_t value);
  private:
  int32_t _internal_n32item4() const;
  void _internal_set_n32item4(int32_t value);
  public:

  // int32 n32item5 = 14;
  void clear_n32item5();
  int32_t n32item5() const;
  void set_n32item5(int32_t value);
  private:
  int32_t _internal_n32item5() const;
  void _internal_set_n32item5(int32_t value);
  public:

  // int32 n32item6 = 15;
  void clear_n32item6();
  int32_t n32item6() const;
  void set_n32item6(int32_t value);
  private:
  int32_t _internal_n32item6() const;
  void _internal_set_n32item6(int32_t value);
  public:

  // int32 n32item7 = 16;
  void clear_n32item7();
  int32_t n32item7() const;
  void set_n32item7(int32_t value);
  private:
  int32_t _internal_n32item7() const;
  void _internal_set_n32item7(int32_t value);
  public:

  // int32 n32item8 = 17;
  void clear_n32item8();
  int32_t n32item8() const;
  void set_n32item8(int32_t value);
  private:
  int32_t _internal_n32item8() const;
  void _internal_set_n32item8(int32_t value);
  public:

  // int32 n32item9 = 18;
  void clear_n32item9();
  int32_t n32item9() const;
  void set_n32item9(int32_t value);
  private:
  int32_t _internal_n32item9() const;
  void _internal_set_n32item9(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb2.titem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stritem0_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stritem1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stritem2_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stritem3_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stritem4_;
    int64_t n64item0_;
    int32_t n32item0_;
    int32_t n32item1_;
    int64_t n64item1_;
    int64_t n64item2_;
    int32_t n32item2_;
    int32_t n32item3_;
    int32_t n32item4_;
    int32_t n32item5_;
    int32_t n32item6_;
    int32_t n32item7_;
    int32_t n32item8_;
    int32_t n32item9_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_lprotobuf_2eproto;
};
// -------------------------------------------------------------------

class titems final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pb2.titems) */ {
 public:
  inline titems() : titems(nullptr) {}
  ~titems() override;
  explicit PROTOBUF_CONSTEXPR titems(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  titems(const titems& from);
  titems(titems&& from) noexcept
    : titems() {
    *this = ::std::move(from);
  }

  inline titems& operator=(const titems& from) {
    CopyFrom(from);
    return *this;
  }
  inline titems& operator=(titems&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const titems& default_instance() {
    return *internal_default_instance();
  }
  static inline const titems* internal_default_instance() {
    return reinterpret_cast<const titems*>(
               &_titems_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(titems& a, titems& b) {
    a.Swap(&b);
  }
  inline void Swap(titems* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(titems* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  titems* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<titems>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const titems& from);
  void MergeFrom(const titems& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(titems* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb2.titems";
  }
  protected:
  explicit titems(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 4,
    kStrtop0FieldNumber = 3,
    kStrtop1FieldNumber = 7,
    kStrtop2FieldNumber = 10,
    kN64Top0FieldNumber = 2,
    kN32Top0FieldNumber = 1,
    kN32Top1FieldNumber = 5,
    kN64Top1FieldNumber = 6,
    kN64Top2FieldNumber = 9,
    kN32Top2FieldNumber = 8,
  };
  // repeated .pb2.titem items = 4;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::pb2::titem* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::titem >*
      mutable_items();
  private:
  const ::pb2::titem& _internal_items(int index) const;
  ::pb2::titem* _internal_add_items();
  public:
  const ::pb2::titem& items(int index) const;
  ::pb2::titem* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::titem >&
      items() const;

  // string strtop0 = 3;
  void clear_strtop0();
  const std::string& strtop0() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_strtop0(ArgT0&& arg0, ArgT... args);
  std::string* mutable_strtop0();
  PROTOBUF_NODISCARD std::string* release_strtop0();
  void set_allocated_strtop0(std::string* strtop0);
  private:
  const std::string& _internal_strtop0() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_strtop0(const std::string& value);
  std::string* _internal_mutable_strtop0();
  public:

  // string strtop1 = 7;
  void clear_strtop1();
  const std::string& strtop1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_strtop1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_strtop1();
  PROTOBUF_NODISCARD std::string* release_strtop1();
  void set_allocated_strtop1(std::string* strtop1);
  private:
  const std::string& _internal_strtop1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_strtop1(const std::string& value);
  std::string* _internal_mutable_strtop1();
  public:

  // string strtop2 = 10;
  void clear_strtop2();
  const std::string& strtop2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_strtop2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_strtop2();
  PROTOBUF_NODISCARD std::string* release_strtop2();
  void set_allocated_strtop2(std::string* strtop2);
  private:
  const std::string& _internal_strtop2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_strtop2(const std::string& value);
  std::string* _internal_mutable_strtop2();
  public:

  // int64 n64top0 = 2;
  void clear_n64top0();
  int64_t n64top0() const;
  void set_n64top0(int64_t value);
  private:
  int64_t _internal_n64top0() const;
  void _internal_set_n64top0(int64_t value);
  public:

  // int32 n32top0 = 1;
  void clear_n32top0();
  int32_t n32top0() const;
  void set_n32top0(int32_t value);
  private:
  int32_t _internal_n32top0() const;
  void _internal_set_n32top0(int32_t value);
  public:

  // int32 n32top1 = 5;
  void clear_n32top1();
  int32_t n32top1() const;
  void set_n32top1(int32_t value);
  private:
  int32_t _internal_n32top1() const;
  void _internal_set_n32top1(int32_t value);
  public:

  // int64 n64top1 = 6;
  void clear_n64top1();
  int64_t n64top1() const;
  void set_n64top1(int64_t value);
  private:
  int64_t _internal_n64top1() const;
  void _internal_set_n64top1(int64_t value);
  public:

  // int64 n64top2 = 9;
  void clear_n64top2();
  int64_t n64top2() const;
  void set_n64top2(int64_t value);
  private:
  int64_t _internal_n64top2() const;
  void _internal_set_n64top2(int64_t value);
  public:

  // int32 n32top2 = 8;
  void clear_n32top2();
  int32_t n32top2() const;
  void set_n32top2(int32_t value);
  private:
  int32_t _internal_n32top2() const;
  void _internal_set_n32top2(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pb2.titems)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::titem > items_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr strtop0_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr strtop1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr strtop2_;
    int64_t n64top0_;
    int32_t n32top0_;
    int32_t n32top1_;
    int64_t n64top1_;
    int64_t n64top2_;
    int32_t n32top2_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_lprotobuf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// titem

// int32 n32item0 = 1;
inline void titem::clear_n32item0() {
  _impl_.n32item0_ = 0;
}
inline int32_t titem::_internal_n32item0() const {
  return _impl_.n32item0_;
}
inline int32_t titem::n32item0() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item0)
  return _internal_n32item0();
}
inline void titem::_internal_set_n32item0(int32_t value) {
  
  _impl_.n32item0_ = value;
}
inline void titem::set_n32item0(int32_t value) {
  _internal_set_n32item0(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item0)
}

// int64 n64item0 = 2;
inline void titem::clear_n64item0() {
  _impl_.n64item0_ = int64_t{0};
}
inline int64_t titem::_internal_n64item0() const {
  return _impl_.n64item0_;
}
inline int64_t titem::n64item0() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n64item0)
  return _internal_n64item0();
}
inline void titem::_internal_set_n64item0(int64_t value) {
  
  _impl_.n64item0_ = value;
}
inline void titem::set_n64item0(int64_t value) {
  _internal_set_n64item0(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n64item0)
}

// string stritem0 = 3;
inline void titem::clear_stritem0() {
  _impl_.stritem0_.ClearToEmpty();
}
inline const std::string& titem::stritem0() const {
  // @@protoc_insertion_point(field_get:pb2.titem.stritem0)
  return _internal_stritem0();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void titem::set_stritem0(ArgT0&& arg0, ArgT... args) {
 
 _impl_.stritem0_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.titem.stritem0)
}
inline std::string* titem::mutable_stritem0() {
  std::string* _s = _internal_mutable_stritem0();
  // @@protoc_insertion_point(field_mutable:pb2.titem.stritem0)
  return _s;
}
inline const std::string& titem::_internal_stritem0() const {
  return _impl_.stritem0_.Get();
}
inline void titem::_internal_set_stritem0(const std::string& value) {
  
  _impl_.stritem0_.Set(value, GetArenaForAllocation());
}
inline std::string* titem::_internal_mutable_stritem0() {
  
  return _impl_.stritem0_.Mutable(GetArenaForAllocation());
}
inline std::string* titem::release_stritem0() {
  // @@protoc_insertion_point(field_release:pb2.titem.stritem0)
  return _impl_.stritem0_.Release();
}
inline void titem::set_allocated_stritem0(std::string* stritem0) {
  if (stritem0 != nullptr) {
    
  } else {
    
  }
  _impl_.stritem0_.SetAllocated(stritem0, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stritem0_.IsDefault()) {
    _impl_.stritem0_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.titem.stritem0)
}

// int32 n32item1 = 4;
inline void titem::clear_n32item1() {
  _impl_.n32item1_ = 0;
}
inline int32_t titem::_internal_n32item1() const {
  return _impl_.n32item1_;
}
inline int32_t titem::n32item1() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item1)
  return _internal_n32item1();
}
inline void titem::_internal_set_n32item1(int32_t value) {
  
  _impl_.n32item1_ = value;
}
inline void titem::set_n32item1(int32_t value) {
  _internal_set_n32item1(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item1)
}

// int64 n64item1 = 5;
inline void titem::clear_n64item1() {
  _impl_.n64item1_ = int64_t{0};
}
inline int64_t titem::_internal_n64item1() const {
  return _impl_.n64item1_;
}
inline int64_t titem::n64item1() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n64item1)
  return _internal_n64item1();
}
inline void titem::_internal_set_n64item1(int64_t value) {
  
  _impl_.n64item1_ = value;
}
inline void titem::set_n64item1(int64_t value) {
  _internal_set_n64item1(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n64item1)
}

// string stritem1 = 6;
inline void titem::clear_stritem1() {
  _impl_.stritem1_.ClearToEmpty();
}
inline const std::string& titem::stritem1() const {
  // @@protoc_insertion_point(field_get:pb2.titem.stritem1)
  return _internal_stritem1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void titem::set_stritem1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.stritem1_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.titem.stritem1)
}
inline std::string* titem::mutable_stritem1() {
  std::string* _s = _internal_mutable_stritem1();
  // @@protoc_insertion_point(field_mutable:pb2.titem.stritem1)
  return _s;
}
inline const std::string& titem::_internal_stritem1() const {
  return _impl_.stritem1_.Get();
}
inline void titem::_internal_set_stritem1(const std::string& value) {
  
  _impl_.stritem1_.Set(value, GetArenaForAllocation());
}
inline std::string* titem::_internal_mutable_stritem1() {
  
  return _impl_.stritem1_.Mutable(GetArenaForAllocation());
}
inline std::string* titem::release_stritem1() {
  // @@protoc_insertion_point(field_release:pb2.titem.stritem1)
  return _impl_.stritem1_.Release();
}
inline void titem::set_allocated_stritem1(std::string* stritem1) {
  if (stritem1 != nullptr) {
    
  } else {
    
  }
  _impl_.stritem1_.SetAllocated(stritem1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stritem1_.IsDefault()) {
    _impl_.stritem1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.titem.stritem1)
}

// int32 n32item2 = 7;
inline void titem::clear_n32item2() {
  _impl_.n32item2_ = 0;
}
inline int32_t titem::_internal_n32item2() const {
  return _impl_.n32item2_;
}
inline int32_t titem::n32item2() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item2)
  return _internal_n32item2();
}
inline void titem::_internal_set_n32item2(int32_t value) {
  
  _impl_.n32item2_ = value;
}
inline void titem::set_n32item2(int32_t value) {
  _internal_set_n32item2(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item2)
}

// int64 n64item2 = 8;
inline void titem::clear_n64item2() {
  _impl_.n64item2_ = int64_t{0};
}
inline int64_t titem::_internal_n64item2() const {
  return _impl_.n64item2_;
}
inline int64_t titem::n64item2() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n64item2)
  return _internal_n64item2();
}
inline void titem::_internal_set_n64item2(int64_t value) {
  
  _impl_.n64item2_ = value;
}
inline void titem::set_n64item2(int64_t value) {
  _internal_set_n64item2(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n64item2)
}

// string stritem2 = 9;
inline void titem::clear_stritem2() {
  _impl_.stritem2_.ClearToEmpty();
}
inline const std::string& titem::stritem2() const {
  // @@protoc_insertion_point(field_get:pb2.titem.stritem2)
  return _internal_stritem2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void titem::set_stritem2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.stritem2_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.titem.stritem2)
}
inline std::string* titem::mutable_stritem2() {
  std::string* _s = _internal_mutable_stritem2();
  // @@protoc_insertion_point(field_mutable:pb2.titem.stritem2)
  return _s;
}
inline const std::string& titem::_internal_stritem2() const {
  return _impl_.stritem2_.Get();
}
inline void titem::_internal_set_stritem2(const std::string& value) {
  
  _impl_.stritem2_.Set(value, GetArenaForAllocation());
}
inline std::string* titem::_internal_mutable_stritem2() {
  
  return _impl_.stritem2_.Mutable(GetArenaForAllocation());
}
inline std::string* titem::release_stritem2() {
  // @@protoc_insertion_point(field_release:pb2.titem.stritem2)
  return _impl_.stritem2_.Release();
}
inline void titem::set_allocated_stritem2(std::string* stritem2) {
  if (stritem2 != nullptr) {
    
  } else {
    
  }
  _impl_.stritem2_.SetAllocated(stritem2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stritem2_.IsDefault()) {
    _impl_.stritem2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.titem.stritem2)
}

// int32 n32item3 = 10;
inline void titem::clear_n32item3() {
  _impl_.n32item3_ = 0;
}
inline int32_t titem::_internal_n32item3() const {
  return _impl_.n32item3_;
}
inline int32_t titem::n32item3() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item3)
  return _internal_n32item3();
}
inline void titem::_internal_set_n32item3(int32_t value) {
  
  _impl_.n32item3_ = value;
}
inline void titem::set_n32item3(int32_t value) {
  _internal_set_n32item3(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item3)
}

// string stritem3 = 11;
inline void titem::clear_stritem3() {
  _impl_.stritem3_.ClearToEmpty();
}
inline const std::string& titem::stritem3() const {
  // @@protoc_insertion_point(field_get:pb2.titem.stritem3)
  return _internal_stritem3();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void titem::set_stritem3(ArgT0&& arg0, ArgT... args) {
 
 _impl_.stritem3_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.titem.stritem3)
}
inline std::string* titem::mutable_stritem3() {
  std::string* _s = _internal_mutable_stritem3();
  // @@protoc_insertion_point(field_mutable:pb2.titem.stritem3)
  return _s;
}
inline const std::string& titem::_internal_stritem3() const {
  return _impl_.stritem3_.Get();
}
inline void titem::_internal_set_stritem3(const std::string& value) {
  
  _impl_.stritem3_.Set(value, GetArenaForAllocation());
}
inline std::string* titem::_internal_mutable_stritem3() {
  
  return _impl_.stritem3_.Mutable(GetArenaForAllocation());
}
inline std::string* titem::release_stritem3() {
  // @@protoc_insertion_point(field_release:pb2.titem.stritem3)
  return _impl_.stritem3_.Release();
}
inline void titem::set_allocated_stritem3(std::string* stritem3) {
  if (stritem3 != nullptr) {
    
  } else {
    
  }
  _impl_.stritem3_.SetAllocated(stritem3, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stritem3_.IsDefault()) {
    _impl_.stritem3_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.titem.stritem3)
}

// int32 n32item4 = 12;
inline void titem::clear_n32item4() {
  _impl_.n32item4_ = 0;
}
inline int32_t titem::_internal_n32item4() const {
  return _impl_.n32item4_;
}
inline int32_t titem::n32item4() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item4)
  return _internal_n32item4();
}
inline void titem::_internal_set_n32item4(int32_t value) {
  
  _impl_.n32item4_ = value;
}
inline void titem::set_n32item4(int32_t value) {
  _internal_set_n32item4(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item4)
}

// string stritem4 = 13;
inline void titem::clear_stritem4() {
  _impl_.stritem4_.ClearToEmpty();
}
inline const std::string& titem::stritem4() const {
  // @@protoc_insertion_point(field_get:pb2.titem.stritem4)
  return _internal_stritem4();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void titem::set_stritem4(ArgT0&& arg0, ArgT... args) {
 
 _impl_.stritem4_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.titem.stritem4)
}
inline std::string* titem::mutable_stritem4() {
  std::string* _s = _internal_mutable_stritem4();
  // @@protoc_insertion_point(field_mutable:pb2.titem.stritem4)
  return _s;
}
inline const std::string& titem::_internal_stritem4() const {
  return _impl_.stritem4_.Get();
}
inline void titem::_internal_set_stritem4(const std::string& value) {
  
  _impl_.stritem4_.Set(value, GetArenaForAllocation());
}
inline std::string* titem::_internal_mutable_stritem4() {
  
  return _impl_.stritem4_.Mutable(GetArenaForAllocation());
}
inline std::string* titem::release_stritem4() {
  // @@protoc_insertion_point(field_release:pb2.titem.stritem4)
  return _impl_.stritem4_.Release();
}
inline void titem::set_allocated_stritem4(std::string* stritem4) {
  if (stritem4 != nullptr) {
    
  } else {
    
  }
  _impl_.stritem4_.SetAllocated(stritem4, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stritem4_.IsDefault()) {
    _impl_.stritem4_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.titem.stritem4)
}

// int32 n32item5 = 14;
inline void titem::clear_n32item5() {
  _impl_.n32item5_ = 0;
}
inline int32_t titem::_internal_n32item5() const {
  return _impl_.n32item5_;
}
inline int32_t titem::n32item5() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item5)
  return _internal_n32item5();
}
inline void titem::_internal_set_n32item5(int32_t value) {
  
  _impl_.n32item5_ = value;
}
inline void titem::set_n32item5(int32_t value) {
  _internal_set_n32item5(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item5)
}

// int32 n32item6 = 15;
inline void titem::clear_n32item6() {
  _impl_.n32item6_ = 0;
}
inline int32_t titem::_internal_n32item6() const {
  return _impl_.n32item6_;
}
inline int32_t titem::n32item6() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item6)
  return _internal_n32item6();
}
inline void titem::_internal_set_n32item6(int32_t value) {
  
  _impl_.n32item6_ = value;
}
inline void titem::set_n32item6(int32_t value) {
  _internal_set_n32item6(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item6)
}

// int32 n32item7 = 16;
inline void titem::clear_n32item7() {
  _impl_.n32item7_ = 0;
}
inline int32_t titem::_internal_n32item7() const {
  return _impl_.n32item7_;
}
inline int32_t titem::n32item7() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item7)
  return _internal_n32item7();
}
inline void titem::_internal_set_n32item7(int32_t value) {
  
  _impl_.n32item7_ = value;
}
inline void titem::set_n32item7(int32_t value) {
  _internal_set_n32item7(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item7)
}

// int32 n32item8 = 17;
inline void titem::clear_n32item8() {
  _impl_.n32item8_ = 0;
}
inline int32_t titem::_internal_n32item8() const {
  return _impl_.n32item8_;
}
inline int32_t titem::n32item8() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item8)
  return _internal_n32item8();
}
inline void titem::_internal_set_n32item8(int32_t value) {
  
  _impl_.n32item8_ = value;
}
inline void titem::set_n32item8(int32_t value) {
  _internal_set_n32item8(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item8)
}

// int32 n32item9 = 18;
inline void titem::clear_n32item9() {
  _impl_.n32item9_ = 0;
}
inline int32_t titem::_internal_n32item9() const {
  return _impl_.n32item9_;
}
inline int32_t titem::n32item9() const {
  // @@protoc_insertion_point(field_get:pb2.titem.n32item9)
  return _internal_n32item9();
}
inline void titem::_internal_set_n32item9(int32_t value) {
  
  _impl_.n32item9_ = value;
}
inline void titem::set_n32item9(int32_t value) {
  _internal_set_n32item9(value);
  // @@protoc_insertion_point(field_set:pb2.titem.n32item9)
}

// -------------------------------------------------------------------

// titems

// int32 n32top0 = 1;
inline void titems::clear_n32top0() {
  _impl_.n32top0_ = 0;
}
inline int32_t titems::_internal_n32top0() const {
  return _impl_.n32top0_;
}
inline int32_t titems::n32top0() const {
  // @@protoc_insertion_point(field_get:pb2.titems.n32top0)
  return _internal_n32top0();
}
inline void titems::_internal_set_n32top0(int32_t value) {
  
  _impl_.n32top0_ = value;
}
inline void titems::set_n32top0(int32_t value) {
  _internal_set_n32top0(value);
  // @@protoc_insertion_point(field_set:pb2.titems.n32top0)
}

// int64 n64top0 = 2;
inline void titems::clear_n64top0() {
  _impl_.n64top0_ = int64_t{0};
}
inline int64_t titems::_internal_n64top0() const {
  return _impl_.n64top0_;
}
inline int64_t titems::n64top0() const {
  // @@protoc_insertion_point(field_get:pb2.titems.n64top0)
  return _internal_n64top0();
}
inline void titems::_internal_set_n64top0(int64_t value) {
  
  _impl_.n64top0_ = value;
}
inline void titems::set_n64top0(int64_t value) {
  _internal_set_n64top0(value);
  // @@protoc_insertion_point(field_set:pb2.titems.n64top0)
}

// string strtop0 = 3;
inline void titems::clear_strtop0() {
  _impl_.strtop0_.ClearToEmpty();
}
inline const std::string& titems::strtop0() const {
  // @@protoc_insertion_point(field_get:pb2.titems.strtop0)
  return _internal_strtop0();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void titems::set_strtop0(ArgT0&& arg0, ArgT... args) {
 
 _impl_.strtop0_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.titems.strtop0)
}
inline std::string* titems::mutable_strtop0() {
  std::string* _s = _internal_mutable_strtop0();
  // @@protoc_insertion_point(field_mutable:pb2.titems.strtop0)
  return _s;
}
inline const std::string& titems::_internal_strtop0() const {
  return _impl_.strtop0_.Get();
}
inline void titems::_internal_set_strtop0(const std::string& value) {
  
  _impl_.strtop0_.Set(value, GetArenaForAllocation());
}
inline std::string* titems::_internal_mutable_strtop0() {
  
  return _impl_.strtop0_.Mutable(GetArenaForAllocation());
}
inline std::string* titems::release_strtop0() {
  // @@protoc_insertion_point(field_release:pb2.titems.strtop0)
  return _impl_.strtop0_.Release();
}
inline void titems::set_allocated_strtop0(std::string* strtop0) {
  if (strtop0 != nullptr) {
    
  } else {
    
  }
  _impl_.strtop0_.SetAllocated(strtop0, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.strtop0_.IsDefault()) {
    _impl_.strtop0_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.titems.strtop0)
}

// repeated .pb2.titem items = 4;
inline int titems::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int titems::items_size() const {
  return _internal_items_size();
}
inline void titems::clear_items() {
  _impl_.items_.Clear();
}
inline ::pb2::titem* titems::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:pb2.titems.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::titem >*
titems::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:pb2.titems.items)
  return &_impl_.items_;
}
inline const ::pb2::titem& titems::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::pb2::titem& titems::items(int index) const {
  // @@protoc_insertion_point(field_get:pb2.titems.items)
  return _internal_items(index);
}
inline ::pb2::titem* titems::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::pb2::titem* titems::add_items() {
  ::pb2::titem* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:pb2.titems.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb2::titem >&
titems::items() const {
  // @@protoc_insertion_point(field_list:pb2.titems.items)
  return _impl_.items_;
}

// int32 n32top1 = 5;
inline void titems::clear_n32top1() {
  _impl_.n32top1_ = 0;
}
inline int32_t titems::_internal_n32top1() const {
  return _impl_.n32top1_;
}
inline int32_t titems::n32top1() const {
  // @@protoc_insertion_point(field_get:pb2.titems.n32top1)
  return _internal_n32top1();
}
inline void titems::_internal_set_n32top1(int32_t value) {
  
  _impl_.n32top1_ = value;
}
inline void titems::set_n32top1(int32_t value) {
  _internal_set_n32top1(value);
  // @@protoc_insertion_point(field_set:pb2.titems.n32top1)
}

// int64 n64top1 = 6;
inline void titems::clear_n64top1() {
  _impl_.n64top1_ = int64_t{0};
}
inline int64_t titems::_internal_n64top1() const {
  return _impl_.n64top1_;
}
inline int64_t titems::n64top1() const {
  // @@protoc_insertion_point(field_get:pb2.titems.n64top1)
  return _internal_n64top1();
}
inline void titems::_internal_set_n64top1(int64_t value) {
  
  _impl_.n64top1_ = value;
}
inline void titems::set_n64top1(int64_t value) {
  _internal_set_n64top1(value);
  // @@protoc_insertion_point(field_set:pb2.titems.n64top1)
}

// string strtop1 = 7;
inline void titems::clear_strtop1() {
  _impl_.strtop1_.ClearToEmpty();
}
inline const std::string& titems::strtop1() const {
  // @@protoc_insertion_point(field_get:pb2.titems.strtop1)
  return _internal_strtop1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void titems::set_strtop1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.strtop1_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.titems.strtop1)
}
inline std::string* titems::mutable_strtop1() {
  std::string* _s = _internal_mutable_strtop1();
  // @@protoc_insertion_point(field_mutable:pb2.titems.strtop1)
  return _s;
}
inline const std::string& titems::_internal_strtop1() const {
  return _impl_.strtop1_.Get();
}
inline void titems::_internal_set_strtop1(const std::string& value) {
  
  _impl_.strtop1_.Set(value, GetArenaForAllocation());
}
inline std::string* titems::_internal_mutable_strtop1() {
  
  return _impl_.strtop1_.Mutable(GetArenaForAllocation());
}
inline std::string* titems::release_strtop1() {
  // @@protoc_insertion_point(field_release:pb2.titems.strtop1)
  return _impl_.strtop1_.Release();
}
inline void titems::set_allocated_strtop1(std::string* strtop1) {
  if (strtop1 != nullptr) {
    
  } else {
    
  }
  _impl_.strtop1_.SetAllocated(strtop1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.strtop1_.IsDefault()) {
    _impl_.strtop1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.titems.strtop1)
}

// int32 n32top2 = 8;
inline void titems::clear_n32top2() {
  _impl_.n32top2_ = 0;
}
inline int32_t titems::_internal_n32top2() const {
  return _impl_.n32top2_;
}
inline int32_t titems::n32top2() const {
  // @@protoc_insertion_point(field_get:pb2.titems.n32top2)
  return _internal_n32top2();
}
inline void titems::_internal_set_n32top2(int32_t value) {
  
  _impl_.n32top2_ = value;
}
inline void titems::set_n32top2(int32_t value) {
  _internal_set_n32top2(value);
  // @@protoc_insertion_point(field_set:pb2.titems.n32top2)
}

// int64 n64top2 = 9;
inline void titems::clear_n64top2() {
  _impl_.n64top2_ = int64_t{0};
}
inline int64_t titems::_internal_n64top2() const {
  return _impl_.n64top2_;
}
inline int64_t titems::n64top2() const {
  // @@protoc_insertion_point(field_get:pb2.titems.n64top2)
  return _internal_n64top2();
}
inline void titems::_internal_set_n64top2(int64_t value) {
  
  _impl_.n64top2_ = value;
}
inline void titems::set_n64top2(int64_t value) {
  _internal_set_n64top2(value);
  // @@protoc_insertion_point(field_set:pb2.titems.n64top2)
}

// string strtop2 = 10;
inline void titems::clear_strtop2() {
  _impl_.strtop2_.ClearToEmpty();
}
inline const std::string& titems::strtop2() const {
  // @@protoc_insertion_point(field_get:pb2.titems.strtop2)
  return _internal_strtop2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void titems::set_strtop2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.strtop2_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb2.titems.strtop2)
}
inline std::string* titems::mutable_strtop2() {
  std::string* _s = _internal_mutable_strtop2();
  // @@protoc_insertion_point(field_mutable:pb2.titems.strtop2)
  return _s;
}
inline const std::string& titems::_internal_strtop2() const {
  return _impl_.strtop2_.Get();
}
inline void titems::_internal_set_strtop2(const std::string& value) {
  
  _impl_.strtop2_.Set(value, GetArenaForAllocation());
}
inline std::string* titems::_internal_mutable_strtop2() {
  
  return _impl_.strtop2_.Mutable(GetArenaForAllocation());
}
inline std::string* titems::release_strtop2() {
  // @@protoc_insertion_point(field_release:pb2.titems.strtop2)
  return _impl_.strtop2_.Release();
}
inline void titems::set_allocated_strtop2(std::string* strtop2) {
  if (strtop2 != nullptr) {
    
  } else {
    
  }
  _impl_.strtop2_.SetAllocated(strtop2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.strtop2_.IsDefault()) {
    _impl_.strtop2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb2.titems.strtop2)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb2

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_lprotobuf_2eproto
