LOCAL_PATH := $(call my-dir)/../../../..

include $(CLEAR_VARS)

LOCAL_MODULE := leagor_basic

LOCAL_CFLAGS := -DBORINGSSL_SHARED_LIBRARY -DBORINGSSL_ALLOW_CXX_RUNTIME -DBORINGSSL_NO_STATIC_INITIALIZER -DOPENSSL_SMALL -DOPENSSL_NO_ASM

LOCAL_CFLAGS += -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
LOCAL_CFLAGS += -O3
# opencv
LOCAL_CFLAGS += -D__OPENCV_BUILD=1 -DWITH_CUDA=OFF
# app extra LOCAL_CFLAGS will insert after it
LOCAL_CFLAGS += -DWITH_OPENSSL

LOCAL_CPPFLAGS += -Wno-inconsistent-missing-override -Wno-nonportable-include-path -Wno-narrowing -Wno-enum-constexpr-conversion -DGOOGLE_PROTOBUF_DONT_USE_UNALIGNED
LOCAL_CPPFLAGS += -std=c++17

LOCAL_CPP_EXTENSION := .cxx .cpp .cc

LOCAL_C_INCLUDES := $(LOCAL_PATH)/external/3rdparty \
	$(LOCAL_PATH)/external/boost \
	$(LOCAL_PATH)/external/boringssl/include \
	$(LOCAL_PATH)/external/libros/include \
	$(LOCAL_PATH)/external/mediapipe \
	$(LOCAL_PATH)/external/opencv \
	$(LOCAL_PATH)/external/opencv/3rdparty/carotene/include \
	$(LOCAL_PATH)/external/opencv/autogenerated \
	$(LOCAL_PATH)/external/protobuf/src \
	$(LOCAL_PATH)/external/tensorflow/tensorflow/lite/downloads/eigen \
	$(LOCAL_PATH)/external/zlib \
	$(LOCAL_PATH)/../linker/include/SDL2 \
	$(LOCAL_PATH)/../linker/include/SDL2_image \
	$(LOCAL_PATH)/../linker/include/SDL2_mixer \
	$(LOCAL_PATH)/../linker/include/SDL2_ttf \
	$(LOCAL_PATH)/libleagor_basic/lsx10/lslidar_driver/include \
	$(LOCAL_PATH)/libleagor_basic/include

LOCAL_SRC_FILES := \
	$(subst $(LOCAL_PATH)/,, \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/ai/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/ai/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/base/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/base/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/dcamera/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/dcamera/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/iot/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/iot/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/laser/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/laser/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/lsx10/lslidar_driver/src/lslidar_driver.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/lsx10/lslidar_driver/src/lslidar_driver_node.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/moveit/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/moveit/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/orbbec/src/ob_camera_node.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/orbbec/src/ob_camera_node_driver.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/orbbec/src/orbbec_ros.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/orbbec/src/ros_sensor.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/orbbec/src/utils.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/rplidar_ros/sdk/src/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/rplidar_ros/sdk/src/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/rplidar_ros/sdk/src/arch/linux/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/rplidar_ros/sdk/src/arch/linux/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/rplidar_ros/src/node.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/sc_mini/src/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/sc_mini/src/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/speech/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/speech/*.cpp) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/task/*.c) \
	$(wildcard $(LOCAL_PATH)/libleagor_basic/task/*.cpp))

# only support 64-bit ABIs
LOCAL_LDFLAGS += -L$(LOCAL_PATH)/../linker/android/lib/arm64-v8a -L$(LOCAL_PATH)/../linker/android/lib-android-private/arm64-v8a

LOCAL_LDLIBS := -lz -llog -landroid -lOpenSLES -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -l3rdparty -lOrbbecSDK
LOCAL_SHORT_COMMANDS := true

include $(BUILD_SHARED_LIBRARY)