LOCAL_PATH := $(call my-dir)/../../../..

include $(CLEAR_VARS)

LOCAL_MODULE := main

LOCAL_CFLAGS := -DWEBRTC_LINUX -DWEBRTC_ANDROID -DWEBRTC_POSIX -DWEBRTC_NS_FIXED -DWEBRTC_APM_DEBUG_DUMP=0 -DWEBRTC_INTELLIGIBILITY_ENHANCER=0 \
-DWEBRTC_CODEC_ISACFX -DHAVE_SCTP -DHAVE_WEBRTC_VIDEO -DHAVE_WEBRTC_VOICE \
-DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DWEBRTC_USE_BUILTIN_ISAC_FIX=1 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=0 \
-DBORINGSSL_SHARED_LIBRARY -DBORINGSSL_ALLOW_CXX_RUNTIME -DBORINGSSL_NO_STATIC_INITIALIZER -DOPENSSL_SMALL -DOPENSSL_NO_ASM \
-DWEBRTC_THREAD_RR -DWEBRTC_OPUS_SUPPORT_120MS_PTIME=1 \
-DNO_TCMALLOC

LOCAL_CFLAGS += -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
ifneq ($(filter $(NDK_KNOWN_DEVICE_ABI64S),$(TARGET_ARCH_ABI)),)
# 64-bit ABIs
LOCAL_CFLAGS += -DWEBRTC_ARCH_ARM64
else
# 32-bit ABIs
LOCAL_CFLAGS += -DWEBRTC_ARCH_ARM -DWEBRTC_ARCH_ARM_V7
endif
LOCAL_CFLAGS += -DWEBRTC_HAS_NEON -DWEBRTC_BUILD_LIBEVENT
LOCAL_CFLAGS += -O3
# opencv
LOCAL_CFLAGS += -D__OPENCV_BUILD=1 -DWITH_CUDA=OFF
# tensorflow lite
LOCAL_CFLAGS += -DEIGEN_MPL2_ONLY -DFLATBUFFERS_LOCALE_INDEPENDENT=1 -DRUY_HAVE_CPUINFO -DCPUINFO_LOG_LEVEL=2 -DTFL_STATIC_LIBRARY_BUILD -DTFLITE_MMAP_DISABLED -DPTHREADPOOL_USE_FASTPATH=1 -DTFLITE_WITH_RUY -DFXDIV_USE_INLINE_ASSEMBLY=0
# mediapipe
LOCAL_CFLAGS += -DMEDIAPIPE_MOBILE -DMEDIAPIPE_BUILD_STATIC_LIBS -DTFL_STATIC_LIBRARY_BUILD -DMEDIAPIPE_DISABLE_GPU=1
# miktex
LOCAL_CFLAGS += -DpdfTeX -DMIKTEX -DMIKTEX_UNIX -DLUATEX_HARFBUZZ_ENABLED
# mupdf
LOCAL_CFLAGS += -DZXING_EXPERIMENTAL_API -DHAVE_ZXINGCPP=1
# zstd
LOCAL_CFLAGS += -DZSTD_STATIC_LINKING_ONLY -DZSTD_DISABLE_ASM
# app extra LOCAL_CFLAGS will insert after it
LOCAL_CFLAGS += -DWITH_OPENSSL

LOCAL_CPPFLAGS += -Wno-inconsistent-missing-override -Wno-nonportable-include-path -Wno-narrowing -Wno-enum-constexpr-conversion -DGOOGLE_PROTOBUF_DONT_USE_UNALIGNED
LOCAL_CPPFLAGS += -std=c++17

LOCAL_CPP_EXTENSION := .cxx .cpp .cc

LOCAL_C_INCLUDES := $(LOCAL_PATH)/external/3rdparty \
	$(LOCAL_PATH)/external/3rdparty/cairo/include \
	$(LOCAL_PATH)/external/3rdparty/cpuinfo/include \
	$(LOCAL_PATH)/external/3rdparty/cpuinfo/src \
	$(LOCAL_PATH)/external/3rdparty/FP16/include \
	$(LOCAL_PATH)/external/3rdparty/FXdiv/include \
	$(LOCAL_PATH)/external/3rdparty/FP16/pffft \
	$(LOCAL_PATH)/external/3rdparty/pthreadpool/include \
	$(LOCAL_PATH)/external/3rdparty/ruy \
	$(LOCAL_PATH)/external/3rdparty/third_party/libyuv/include \
	$(LOCAL_PATH)/external/3rdparty/third_party/libsrtp/include \
	$(LOCAL_PATH)/external/3rdparty/third_party/libsrtp/crypto/include \
	$(LOCAL_PATH)/external/3rdparty/usrsctplib \
	$(LOCAL_PATH)/external/3rdparty/zlib \
	$(LOCAL_PATH)/external/3rdparty/zxing \
	$(LOCAL_PATH)/external/base/third_party/libevent/android \
	$(LOCAL_PATH)/external/boost \
	$(LOCAL_PATH)/external/boringssl/include \
	$(LOCAL_PATH)/external/chromium \
	$(LOCAL_PATH)/external/chromium/third_party/abseil-cpp \
	$(LOCAL_PATH)/external/live555 \
	$(LOCAL_PATH)/external/mediapipe \
	$(LOCAL_PATH)/external/opencv \
	$(LOCAL_PATH)/external/opencv/3rdparty/carotene/include \
	$(LOCAL_PATH)/external/opencv/autogenerated \
	$(LOCAL_PATH)/external/protobuf/src \
	$(LOCAL_PATH)/external/tensorflow \
	$(LOCAL_PATH)/external/tensorflow/tensorflow/lite/downloads/eigen \
	$(LOCAL_PATH)/external/tensorflow/tensorflow/lite/downloads/gemmlowp \
	$(LOCAL_PATH)/external/tensorflow/tensorflow/lite/downloads/farmhash/src \
	$(LOCAL_PATH)/external/tensorflow/tensorflow/lite/downloads/flatbuffers/include \
	$(LOCAL_PATH)/external/tensorflow/third_party/xla \
	$(LOCAL_PATH)/external/tensorflow/XNNPACK \
	$(LOCAL_PATH)/external/tensorflow/XNNPACK/include \
	$(LOCAL_PATH)/external/webrtc \
	$(LOCAL_PATH)/external/webrtc/common_audio/signal_processing/include \
	$(LOCAL_PATH)/external/webrtc/modules/audio_coding/codecs/isac/main/include \
	$(LOCAL_PATH)/../linker/include/SDL2 \
	$(LOCAL_PATH)/../linker/include/SDL2_image \
	$(LOCAL_PATH)/../linker/include/SDL2_mixer \
	$(LOCAL_PATH)/../linker/include/SDL2_ttf \
	$(LOCAL_PATH)/../linker/include/libvpx \
	$(LOCAL_PATH)/../linker/include/kos \
	$(LOCAL_PATH)/librose \
	$(LOCAL_PATH)/kdesktop \
	$(LOCAL_PATH)/external/freerdp/channels/client \
	$(LOCAL_PATH)/external/freerdp/include \
	$(LOCAL_PATH)/external/freerdp/out \
	$(LOCAL_PATH)/external/freerdp/out/include \
	$(LOCAL_PATH)/external/freerdp/out/winpr/include \
	$(LOCAL_PATH)/external/freerdp/winpr/include \
	$(LOCAL_PATH)/external/freerdp/winpr/libwinpr/utils \
	$(LOCAL_PATH)/external/freerdp/winpr/libwinpr/utils/trio

LOCAL_SRC_FILES := \
	$(subst $(LOCAL_PATH)/,, \
	$(wildcard $(LOCAL_PATH)/kdesktop/*.c) \
	$(wildcard $(LOCAL_PATH)/kdesktop/*.cc) \
	$(wildcard $(LOCAL_PATH)/kdesktop/*.cpp) \
	$(wildcard $(LOCAL_PATH)/kdesktop/gui/dialogs/*.c) \
	$(wildcard $(LOCAL_PATH)/kdesktop/gui/dialogs/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/*.cc) \
	$(wildcard $(LOCAL_PATH)/librose/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/event/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/event/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/iterator/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/iterator/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/widget_Definition/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/widget_Definition/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/window_Builder/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/gui/auxiliary/window_Builder/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/gui/dialogs/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/gui/dialogs/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/gui/lib/types/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/gui/lib/types/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/gui/widgets/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/gui/widgets/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/minizip/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/minizip/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/ocr/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/ocr/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/scripts/gui/dialogs/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/scripts/gui/dialogs/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/scripts/gui/widgets/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/scripts/gui/widgets/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/scripts/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/scripts/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/serialization/*.c) \
	$(wildcard $(LOCAL_PATH)/librose/serialization/*.cpp) \
	$(wildcard $(LOCAL_PATH)/librose/tinyxml2/tinyxml2.cpp))


include $(LOCAL_PATH)/external/3rdparty/cpuinfo/Android.mk
include $(LOCAL_PATH)/external/3rdparty/expat/Android.mk
include $(LOCAL_PATH)/external/3rdparty/jpeg-9f/Android.mk
include $(LOCAL_PATH)/external/3rdparty/pthreadpool/Android.mk
include $(LOCAL_PATH)/external/3rdparty/ruy/Android.mk
include $(LOCAL_PATH)/external/3rdparty/third_party/libyuv/Android.mk
include $(LOCAL_PATH)/external/3rdparty/third_party/libsrtp/Android.mk
include $(LOCAL_PATH)/external/3rdparty/usrsctplib/Android.mk
include $(LOCAL_PATH)/external/3rdparty/zstd/Android.mk
# include $(LOCAL_PATH)/external/3rdparty/zxing/Android.mk
include $(LOCAL_PATH)/external/chromium/third_party/abseil-cpp/Android.mk
include $(LOCAL_PATH)/external/chromium/Android-android.mk
include $(LOCAL_PATH)/external/live555/Android.mk
include $(LOCAL_PATH)/external/base/third_party/libevent/Android.mk
include $(LOCAL_PATH)/external/tensorflow/Android.mk
include $(LOCAL_PATH)/external/mediapipe/Android.mk

WEBRTC_SUBPATH := external/webrtc
include $(LOCAL_PATH)/$(WEBRTC_SUBPATH)/Android-android.mk
# app extra external mk will insert after it
include $(LOCAL_PATH)/external/freerdp/Android-client.mk

ifneq ($(filter $(NDK_KNOWN_DEVICE_ABI64S),$(TARGET_ARCH_ABI)),)
# 64-bit ABIs
LOCAL_LDFLAGS += -L$(LOCAL_PATH)/../linker/android/lib/arm64-v8a -L$(LOCAL_PATH)/../linker/android/lib-android-private/arm64-v8a
else
# 32-bit ABIs
LOCAL_LDFLAGS += -L$(LOCAL_PATH)/../linker/android/lib/armeabi-v7a -L$(LOCAL_PATH)/../linker/android/lib-android-private/armeabi-v7a
endif

LOCAL_LDFLAGS += ${LOCAL_PATH}/external/chromium/base/android/library_loader/anchor_functions.lds
LOCAL_LDLIBS := -lz -llog -landroid -lOpenSLES -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -l3rdparty
LOCAL_SHORT_COMMANDS := true

include $(BUILD_SHARED_LIBRARY)